console.log("+++++++++++++++++++++++++++++++++++ starting MightyText CRX +++++++++++++++++++++++++++++++++++\n\n");setBrowserActionIcon("default-icon-on-background-start");
var baseUrl="https://textyserver.appspot.com",contactsFromPhoneGlobal=[],manifest=chrome.runtime.getManifest(),globalIntervalGetPhoneStatus,webapp_crx_globalUserSettingsUponCRXLoad,username_prefix_jstrg_purpose,google_username_currently_logged_in,isAProUser=!1,global_time_last_push_rcvd=new Date,webapp_crx_time_last_channel_token_obtained=new Date,webapp_crx_time_last_successful_health_check_received=new Date,time_last_success_mighty_ping=new Date,notify_android_app_install_once=!1,globalPHONEContactsRefreshCacheQueue=
[],signInUrlCRX=baseUrl+"/signin?extret="+encodeURIComponent(chrome.extension.getURL("help.html"))+"%23signed_in&ver="+manifest.version,registerUrl=baseUrl+"/register?ver="+manifest.version,NEW_COUNT_GLOBAL_NOTIF=0,global_count_request_phone_status=0,deviceNotifManagerArray={},sourceClient=32,capi_helper_global_login_state="UNKNOWN",globalMsUntilShowNotLoggedInNotifAgain=36E5,globalLastKnownSystemStatus="UNKNOWN",globalSystemIdleStatusThresholdInSeconds=60,globalUserOS="unknown",_gaq=_gaq||[];
_gaq.push(["_setAccount","UA-21391541-14"]);(function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src="https://ssl.google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();var _kmq=_kmq||[],_kmk=_kmk||"a009d9e3633da7d7456e8e1478c8f05f33e35f8e";
function _kms(a){setTimeout(function(){var b=document,c=b.getElementsByTagName("script")[0];b=b.createElement("script");b.type="text/javascript";b.async=!0;b.src=a;c.parentNode.insertBefore(b,c)},1)}_kms("https://i.kissmetrics.com/i.js");_kms("https://scripts.kissmetrics.com/"+_kmk+".2.js");_kms("../scripts/km_secure.js");
(function(){var a=window,b=a.Intercom;if("function"===typeof b)b("reattach_activator"),b("update",intercomSettings);else{b=function(){var a=c.createElement("script");a.type="text/javascript";a.async=!0;a.src="https://widget.intercom.io/widget/7guo5kws";var b=c.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)};var c=document,d=function(){d.c(arguments)};d.q=[];d.c=function(a){d.q.push(a)};a.Intercom=d;a.attachEvent?a.attachEvent("onload",b):a.addEventListener("load",b,!1)}})();setGlobalLastKnownSystemStatus();
var globalHeartbeatInterval=setInterval(doHeartBeatCheckWhenUserIsNotLoggedIn,1E4),globalBrowserActionIconCheckerInterval=setInterval(function(){backupBrowserActionIconChecker()},3E5),globalLockedNotificationCleanupInterval=setInterval(clearOldLockedChromeNotificationsFromTray,6E4);17===getRandomInt(0,100)&&_gaq.push(["_trackEvent","Background","Startup-BG-Script-1pct-Sample",manifest.version]);setNetworkEventListenersAndGlobalAjaxMethods();var flushedJstorageOnce=window.localStorage.crx_upgrade_jstorage_flushed;
if(!flushedJstorageOnce)throw $.jStorage.flush(),window.localStorage.crx_upgrade_jstorage_flushed=1,setTimeout(function(){forceReloadCRX("Flushed-Jstorage")},1E3),console.log("javascript should stop executing now."),Error("Stopping JS to restart the CRX before any new jstorage values are set.");checkGoogleLoginTokenAndSetUserName(1,!0);setUserGlobalOS();function setUserGlobalOS(){chrome.runtime.getPlatformInfo(function(a){"mac"==a.os?globalUserOS="Mac":"win"==a.os&&(globalUserOS="Windows")})}$(document).ready(doCRXLocalStorageSetCRXIsAlive);
function doHeartBeatCheckWhenUserIsNotLoggedIn(){console.log("User is not logged in.  Checking when we last successfully made a request to textyserver.");checkLastMightyNetworkPing()}
function checkLastMightyNetworkPing(){var a=((new Date).getTime()-time_last_success_mighty_ping.getTime())/1E3;console.log("--------------\x3e Seconds Since LAST MightyText network ping: "+a);3600<a&&(colorConsole("---\x3e has been a long time since last MT ping -- try to contact google.com first","red"),$.ajax({type:"GET",url:"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js",dataType:"text",cache:!1,success:function(a){console.log("Network ping to Google -- fine...");console.log("User is not logged in and there is an internet connection, but we have not received a response from texty server for over 60 minutes.  Will reload CRX BG in 10 seconds.");
forceReloadCRX("Checking-Last-MightyNetwork-Ping")}}))}function doHeartBeatCheckWhenUserIsLoggedIn(){checkWhenWasLastSuccessfulPUSH();checkLastMightyNetworkPing();console.log("-------------------------\x3e Heartbeat WEBAPP USER @ "+Date()+" ###")}
function checkGoogleLoginTokenAndSetUserName(a,b){a||(a=1);var c=baseUrl+"/api?function=getUserInfoFull"+buildClientSpecificRequestParamsForLogging(!0);$.ajax({url:c,type:"GET",timeout:5E3,dataType:"json",error:function(b,c,f){!navigator.onLine&&3>=a?(setBrowserActionIcon("no-internet"),initializeAppHealthCheck()):(console.log("On retry attempt #"+a+" -- ERROR in AJAX in getUserInfoFull: "+f),3<a?checkRegularInternetConnection(errorBroadcastGetUserInfo,initializeAppHealthCheck):window.setTimeout(function(){checkGoogleLoginTokenAndSetUserName(a+
1)},2E3))},success:function(a,b,c){console.log(a);time_last_success_mighty_ping=new Date;a.user&&-1<a.user.indexOf("user not logged in")?(1>Math.floor(100*Math.random())&&_gaq.push(["_trackEvent","CRX-Background","Error","User-Not-Logged-In-CRX-1Pct-Sample",1]),createUserNotLoggedInNotification(),setBrowserActionIcon("user-not-logged-in")):a.user_info_full&&0<a.user_info_full.email.length?(999==a.user_info_full.premium?isAProUser=!0:1==a.user_info_full.premium&&a.billing_info&&(billingInfo=a.billing_info,
"active"==a.billing_info.status||"past_due"==a.billing_info.status||"trialing"==a.billing_info.status)&&(isAProUser=!0),globalUserName=google_username_currently_logged_in=a.user_info_full.email,c=a.user_info_full.ts_creation,b=new Date,checkIfUserHasGivenConsentForLatestTOSPP(),_kmq.push(["identify",google_username_currently_logged_in]),doIntercomSetup(google_username_currently_logged_in,c,a,"CRX-MODERN-USER"),b=b.setHours(0,0,0,0),c=$.jStorage.get("ts_last_kissmetrics_login_call","no-km-last-login-set"),
"no-km-last-login-set"==c&&_gaq.push(["_trackEvent","Background","CRX-KM-Last-TS",c]),c==b?6>Math.floor(10*Math.random())&&(_kmq.push(["record","User Logged In",{"CRX-Login":"true",Client:"CRX","Dup-Intraday":"true"}]),$.jStorage.set("ts_last_kissmetrics_login_call",b)):(_kmq.push(["record","User Logged In",{"CRX-Login":"true",Client:"CRX","Dup-Intraday":"false",crx_login_version:manifest.version}]),Intercom("trackEvent","User-Logged-In-CRX",{Client:"CRX","App-Version":manifest.version}),$.jStorage.set("ts_last_kissmetrics_login_call",
b),recordMTStatsEvent({event:{name:"event_client_metric",options:{type:"logged-in"}}})),void 0!=a.user_info_full.channelapi_enabled&&100==a.user_info_full.channelapi_enabled&&(username_prefix_jstrg_purpose=a.user_info_full.email.substr(0,a.user_info_full.email.indexOf("@")),initializeCRXForLoggedInUser(a.user_info_full),10>getRandomInt(0,100)&&_gaq.push(["_trackEvent","Background","CRX-User-Logged-In-10pct-Sample",manifest.version.toString()]),processHostedInstructions())):(-1!=a.user_status.search("not registered")?
(liveNotifyGetUserStatus("NOT-REG"),"email"in a&&(globalUserName=a.email),notify_android_app_install_once||(a=determineIfNotifShouldRequireInteractionBasedOnOS({notif_options:{type:"basic",priority:2,title:getLocalizedAppString({key:"install_mt_notif_title"}),message:getLocalizedAppString({key:"install_mt_notif_content"}).replace("%user_email%",a.email),contextMessage:getLocalizedAppString({key:"click_for_instructions"})+".",iconUrl:"../img/48x48_MT_logo_boom_gradient_white.png"}}),chrome.notifications.create("user-install-android-app",
a,function(a){recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:"user-install-android-app"}});genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!1,notif_sound:!0});console.log('just created a notif with the ID: "'+a+'"')}),notify_android_app_install_once=!0)):(a=determineIfNotifShouldRequireInteractionBasedOnOS({notif_options:{type:"basic",priority:2,title:"MightyText",message:getLocalizedAppString({key:"mt_gen_error_notif_content"}),iconUrl:"../img/notifications/error_icon.png"}}),
chrome.notifications.create("getuserinfofull-general-error",a,function(a){recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:"getuserinfofull-general-error"}});genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!1,notif_sound:!0})})),setBrowserActionIcon("user-not-logged-in"))}})}function liveNotifyGetUserStatus(a){2>Math.floor(80*Math.random())&&_kmq.push(["record","CRX-UserState-"+a])}
function doIntercomSetup(a,b,c,d){b=Math.round((new Date(b)).getTime()/1E3);var e=c.user_info_full.current_app_version,f=Math.round((new Date(c.user_info_full.ts_last_login)).getTime()/1E3),h=c.user_info_full.ts_first_login,g=Math.round((new Date(h)).getTime()/1E3);console.log(c);intercomSettings={email:a,created_at:b,app_id:"7guo5kws",web_app:d,phone_app_version:e,ts_last_login_at:f,wagda:"DEC-2017",app_version:manifest.version,pro_user:"NO","day-last-seen":getCurrentWeekdayName()};void 0!=h&&(intercomSettings.ts_first_login_at=
g);isAProUser&&(intercomSettings.pro_user="YES");c.billing_info&&(intercomSettings.plan_id=c.billing_info.plan_id);c.user_info_full.phone_lang&&(intercomSettings["phone-lang"]=c.user_info_full.phone_lang);window.Intercom("boot",intercomSettings)}
function initializeCRXForLoggedInUser(a){setTimeout(function(){checkNewsNotifications(a)},5E3);addContextMenusAndPageAction();setBrowserActionIcon("user-logged-in");getPhoneContactsFromServer();liveNotifyGetUserStatus("REG-OK");clearInterval(globalHeartbeatInterval);globalHeartbeatInterval=setInterval(doHeartBeatCheckWhenUserIsLoggedIn,2E4);___getPhoneStatus(!0);checkForExistingPhoneLiveViewPopout({get_latest_notifs_for_existing:!0});clearInterval(globalIntervalGetPhoneStatus);globalIntervalGetPhoneStatus=
setInterval(___getPhoneStatus,24E4);checkNotifDisplaySettingsAndNotifyUser();fetchUserAppInfo({attempt:0});setTimeout(checkIfUserIsCompatibleWithOurDefaultPushProvider,timeBeforeCheckForPushServiceEnabled);getThreadsAndPopulateJStorage();initializeAppHealthCheck();getLocalJStorageSettings({environment:"background"});checkIfUserIsInReminderExperiment(a);storeGetUserInfoFullDetails({details:a})}
function storeGetUserInfoFullDetails(a){a=a.details;a.hasOwnProperty("current_app_version")&&(window.localStorage.current_phone_app_version=a.current_app_version);window.localStorage.is_pro=isAProUser;a.hasOwnProperty("my_referral_code")&&(window.localStorage[username_prefix_jstrg_purpose+"|referral_url"]="http://mightytext.net/"+a.my_referral_code)}
function getThreadsAndPopulateJStorage(a){"undefined"===typeof a&&(a=0);colorConsole("trying to call getThreads! Try count: "+a);$.ajax({url:baseUrl+"/api?function=GetDistinctMessageHeaders&CLIENT=CRX",type:"GET",timeout:1E4,dataType:"json",error:function(b,c,d){1>a?(a++,getThreadsAndPopulateJStorage(a)):checkRegularInternetConnection(errorGetDistinctHeaders)},success:function(a,c,d){$.each(a.messages,function(a,b){0==b.phone_num_clean&&(b.phone_num="Unknown / Misc");var c=$.jStorage.get(username_prefix_jstrg_purpose+
"|PC_"+b.phone_num_clean,"no-jstorage-val-found");"no-jstorage-val-found"==c?(c=getSinglePhoneContactInfo(b.phone_num_clean),console.log("NO LOCAL JSTORAGE CONTACT NAME MATCH FOR PHONE_NUM_CLEAN: "+b.phone_num_clean+" ... now check array loaded from cloud")):console.log("MATCHED! LOCAL JSTORAGE CONTACT NAME MATCH FOR PHONE_NUM_CLEAN: "+b.phone_num_clean);void 0==c?colorConsole("contactobj is undefined.  phone num clean: "+b.phone_num_clean,"red"):(c=$.jStorage.get(username_prefix_jstrg_purpose+"|PH_PIC_"+
b.phone_num_clean,"no-jstorage-val-found"),"no-jstorage-val-found"==c?(setTimeout(function(){getContactImageFromCloudAndSetJStorage(b.phone_num,b.phone_num_clean)},500*a),console.log("NO CONTACT PHOTO LOCAL JSTORAGE MATCH FOR PHONE_NUM_CLEAN: "+b.phone_num_clean)):console.log("CONTACT PHOTO MATCH LOCAL JSTORAGE MATCH FOR PHONE_NUM_CLEAN: "+b.phone_num_clean))})}})}
function OLD_asyncLoopThroughLocalStoragePHONEThumbnailsAndDisplay(){if(1>globalPHONEContactsRefreshCacheQueue.length)return!1;var a=globalPHONEContactsRefreshCacheQueue.shift(),b=a[1];$("#thumbnail-if-known-"+a[0]).attr("src",b);0<globalPHONEContactsRefreshCacheQueue.length&&setTimeout(asyncLoopThroughLocalStoragePHONEThumbnailsAndDisplay,100)}
function getContactImageFromCloudAndSetJStorage(a,b,c){$.ajax({url:baseUrl+"/phonecontact",type:"POST",data:{"function":"getPhoneContactPhotos",phone_num_clean:b,phone_num_full:a},dataType:"json",success:function(a,c,f){0<a.phone_contact_photo_status.length&&(c=a.phone_contact_photo_status,a="0"==a.phone_contact_photo_status?2:"NO_PHOTO"==c?7:30,colorConsole("Thumbnail returned for: "+b+", at "+new Date+"storing it for: "+a+" days. ","red"),$.jStorage.set(username_prefix_jstrg_purpose+"|PH_PIC_"+
b,{contactThumbnailBinary:c},{TTL:864E5*a}))}})}function getPhoneContactsFromServer(a){$.ajax({url:baseUrl+"/phonecontact?function=getPhoneContacts",type:"GET",dataType:"json",success:function(b,c,d){processPhoneContacts(b);a&&a()}})}
function processPhoneContacts(a){if(0==a.contacts_status)return colorConsole("No Phone contacts in cloud for this user","red"),!1;$.each(a,function(a,c){var b="";c.hasOwnProperty("contactId");c.hasOwnProperty("displayName")&&(b=c.displayName);c.hasOwnProperty("phoneList")&&$.each(c.phoneList,function(a,c){var d="",e="";c.hasOwnProperty("type")&&(d=c.type);c.hasOwnProperty("phoneNumber")&&(e=c.phoneNumber);cleanPhoneNum=getSanitizedPhoneNumberRemoveHyphensParenthesisSpaces(e);contactsFromPhoneGlobal.push({phoneNum:e,
phoneNumType:d,phoneNumClean:cleanPhoneNum,contactName:b})})})}
function checkRegularInternetConnection(a,b){$.ajax({type:"GET",url:"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js",cache:!1,dataType:"text",timeout:8E3,success:function(b,d,e){colorConsole("CheckRegularInternetConnection succeeded!","#74AAD8","14px");a&&a()},error:function(){b&&b();colorConsole("Error:  Unable to fetch "+this.url+", so there must be an issue with the user's internet connectivity","#74AAD8","14px")}})}
function sendOtherC2DM(a,b,c,d){var e=baseUrl+"/client";b={"function":"send",deviceType:"ac2dm",source_client:32,action:a,action_data:b};c&&(b.extra_param=c);console.log("send url for Custom C2DM is: "+e);console.log("post vars string: ",b);$.ajax({url:e,type:"POST",data:b,dataType:"text",timeout:8E3,success:function(b,e,g){time_last_success_mighty_ping=new Date;-1<b.search("sent to phone")?"fetch_binary_from_url_store_on_device"==a||"launch_from_url"==a||"send_snippet_to_phone"==a?alertWeb2PhoneOfSendC2DMSuccess(d,
!0):"push_phone_contacts_to_cloud"==a&&c&&"user-clicked-clear-contacts-button-so-flush-jstorage"==c&&notifyOptionsPageOfContactRefreshResponse(!0):("fetch_binary_from_url_store_on_device"==a||"launch_from_url"==a||"send_snippet_to_phone"==a?alertWeb2PhoneOfSendC2DMSuccess(d,!1):"push_phone_contacts_to_cloud"==a&&c&&"user-clicked-clear-contacts-button-so-flush-jstorage"==c&&notifyOptionsPageOfContactRefreshResponse(!1),handleC2DM_GCM_Errors(a,b))},error:function(b,e,g){"fetch_binary_from_url_store_on_device"==
a||"launch_from_url"==a||"send_snippet_to_phone"==a?alertWeb2PhoneOfSendC2DMSuccess(d,!1):"push_phone_contacts_to_cloud"==a&&c&&"user-clicked-clear-contacts-button-so-flush-jstorage"==c&&notifyOptionsPageOfContactRefreshResponse(!1);console.log("Error in C2DM: "+g);console.log("Error details: "+g.error)}})}
function checkNewsNotifications(a){var b=manifest.version,c=[];c["10.2"]=[];c["10.2"].headline="New! Instantly send pictures from your computer to your phone";c["10.2"].body="\r\nJust right-click on an image on any web page and select 'Send Image to your Phone' and you will see it on your phone instantly.\r\n ";c["12.4"]=[];c["12.4"].headline="New! Text web pages & photos directly from Chrome";c["12.4"].body="Click to learn more.";c["12.5"]=[];c["12.5"].headline="New! Send (almost) anything to your phone";
c["12.5"].body="Instantly send web pages, maps, text snippets, and more...\n\nClick here for details.";c["13.0"]=[];c["13.0"].headline="New Extension Options!";c["13.0"].body="Set preferences for Notifications of incoming messages, phone apps, and more...";c["13.0"].extended_content="Click here to try!";c["15.0"]=[];c["15.0"].headline="New in MightyText Chrome Extension";c["15.0"].body="Notification Sounds, Quick Notification Toggle, New Settings options.";c["15.0"].extended_content="Click to learn more...";
c["15.1"]=[];c["15.1"].headline="Testing";c["15.1"].body="Testing123";a=(new Date(a.ts_creation)).getTime();a=((new Date).getTime()-a)/864E5;if(c[b]&&1<a)if("1"==$.jStorage.get("news_"+b,"no-news-shown-yet"))console.log("news for this version has already been seen");else{a=determineIfNotifShouldRequireInteractionBasedOnOS({notif_options:{type:"basic",title:c[b].headline,message:c[b].body,contextMessage:buildIncomingMessageContextMessage(),iconUrl:"../img/48x48_MT_logo_boom_gradient_white.png",priority:2}});
var d="news_notif_"+b;void 0!=c[b].extended_content&&(a.contextMessage=c[b].extended_content);chrome.notifications.create(d,a,function(a){$.jStorage.set("news_"+b,"1");recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:d}});genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!1,notif_sound:!0});_gaq.push(["_trackEvent","CRX",a,"Impression"])})}else console.log("no news found for this version.")}
function setBrowserActionIcon(a){var b={},c={},d={};"no-internet"==a||"default-icon-on-background-start"==a?(chrome.contextMenus.removeAll(function(){console.log("user is not logged in/there is no internet connectivity, so we should remove all context menus")}),b.path={19:"../img/19x19MT_logo_no_int_conn.png",38:"../img/38x38MT_logo_no_int_conn.png"},d.title="MightyText\n"+getLocalizedAppString({key:"browser_action_no_int"}),c.popup="../html/generic.html"):"user-not-logged-in"==a?(chrome.contextMenus.removeAll(function(){console.log("user is not logged in/there is no internet connectivity, so we should remove all context menus")}),
b.path={19:"../img/19x19-mt-signed-out.png",38:"../img/38x38-mt-signed-out.png"},d.title="MightyText\n"+getLocalizedAppString({key:"browser_action_no_cookie"}),chrome.browserAction.onClicked.removeListener(userNotLoggedInBrowserActionClicked),chrome.browserAction.onClicked.addListener(userNotLoggedInBrowserActionClicked),c.popup=""):"user-logged-in"==a?(c.popup="../html/popup.html",window.localStorage.global_notifications&&"0"==window.localStorage.global_notifications?(b.path={19:"../img/19x19-mt-notif-off.png",
38:"../img/38x38-mt-notif-off.png"},d.title="MightyText\n"+getLocalizedAppString({key:"browser_action_global_notifs_off"})):window.localStorage.message_notifications&&"0"==window.localStorage.message_notifications?(b.path={19:"../img/19x19-mt-notif-off.png",38:"../img/38x38-mt-notif-off.png"},d.title="MightyText\n"+getLocalizedAppString({key:"browser_action_msg_notifs_off"})):(b.path={19:"../img/19x19_MT_logo_boom_gradient_white.png",38:"../img/38x38_MT_logo_boom_gradient_white.png"},d.title="MightyText\n"+
getLocalizedAppString({key:"browser_action_logged_in"}))):"cannot-connect-to-textyserver"==a&&(chrome.contextMenus.removeAll(function(){console.log("user is not logged in/there is no internet connectivity, so we should remove all context menus")}),c.popup="../html/generic.html",b.path={19:"../img/19x19_cant_reach_mt.png",38:"../img/38x38_cant_reach_mt.png"},d.title="MightyText\n"+getLocalizedAppString({key:"browser_action_unable_to_connect"}));chrome.browserAction.setPopup(c);chrome.browserAction.setTitle(d);
chrome.browserAction.setIcon(b)}function userNotLoggedInBrowserActionClicked(){_kmq.push(["record","user-clicked-browser-action-icon",{browser_action_btn_state:"user-not-logged-in"}]);openSignInURLInNewTab()}
function goToActiveMightyTextTab(){chrome.tabs.query({currentWindow:!0,url:"https://mightytext.net/*"},function(a){0<a.length?$(a).each(function(b,c){var d=c.url;console.log(c);if(-1<d.indexOf("mightytext.net/web")||-1<d.indexOf("mightytext.net/app"))return chrome.tabs.update(c.id,{active:!0},function(){console.log("User focused in MT App")}),!1;b+1==a.length&&chrome.tabs.create({active:!0,url:"https://mightytext.net/"+currentProductionPath},function(){console.log("new tab of MightyText WebApp created.")})}):
chrome.tabs.create({active:!0,url:"https://mightytext.net/"+currentProductionPath},function(){console.log("new tab of MightyText WebApp created.")})})}
function checkUserLoginStatusAfterPUSHNotifyLogout(a){$.ajax({url:baseUrl+"/api?function=getUserInfoFull&CLIENT=CRX",type:"GET",timeout:1E4,dataType:"json",error:function(a,c,d){console.log("ERROR in AJAX in getUserInfoFull: "+d)},success:function(b,c,d){console.log(b);b.user_info_full&&0<b.user_info_full.email.length?a?(chrome.notifications.clear("user_not_logged_in"),forceReloadCRX("User-Signed-In-From-Another-Client")):setBrowserActionIcon("user-logged-in"):"user not logged in"==b.user&&forceReloadCRX("User-Signed-Out-From-Another-Client")}})}
chrome.runtime.onMessage.addListener(function(a,b,c){a.new_notify_background_that_user_is_logged_in?(forceReloadCRX("User-Signed-In-From-CRX"),c({reply:"successful_user_login"})):a.notify_crx_from_webapp_signin?(checkUserLoginStatusAfterPUSHNotifyLogout(!0),c({reply:"notify_crx_from_webapp_signin"})):a.setProperBrowserActionIcon?(setBrowserActionIcon("user-logged-in"),c({reply:"setting_browser_action_icon"})):a.reloadCRX?(forceReloadCRX(a.reloadReason),c({reply:"reloading_crx_now"})):a.userClickedClearContactsButton?
(sendOtherC2DM("push_phone_contacts_to_cloud","na","user-clicked-clear-contacts-button-so-flush-jstorage"),c({reply:"request_made_phone"})):a.handle_gcm_error?(a.hasOwnProperty("details")&&a.details.hasOwnProperty("action")&&a.details.hasOwnProperty("server_resp")?(b={received_request_to_handle_gcm_error:!0},handleC2DM_GCM_Errors(a.details.action,a.details.server_resp)):(console.error(a),b={error_with_message_to_handle_gcm_errors:!0}),c(b)):a.hasOwnProperty("get_username_prefix")?c({username_prefix:username_prefix_jstrg_purpose}):
a.hasOwnProperty("user_loaded_phone_notif_live_view")?checkIfUserHasAHealthyPUSHSocket():a.hasOwnProperty("check_user_pro_status")?c({user_is_pro:isAProUser}):a.hasOwnProperty("user_consented_to_tos_pp_update")?(console.info(a),recordUserTOSPPConsent(a),recordTOSPPUpdateAnalyticsEvent({action:"consent",ip_info:a.ip_info})):a.hasOwnProperty("record_mt_stats_event")&&("notif_event"in a&&recordNotificationAnalyticsEvent({options:a.event_options}),c({rcvd_request_to_record_mt_event:!0}))});
function checkIfUserHasAHealthyPUSHSocket(){setTimeout(function(){if("undefined"!=typeof global_time_last_push_rcvd){var a=new Date,b=(a-global_time_last_push_rcvd)/1E3,c="false",d={ts_last_capi_rcvd_lt_30_secs_ago:!1};30>b&&(c="true",d.ts_last_capi_rcvd_lt_30_secs_ago=!0);console.info("checking when the last time a user received a PUSH to determine if they have a healthy PUSH socket",{now:a,ts_last_capi_rcvd:global_time_last_push_rcvd,time_diff:b});console.info("last push rcvd analytics event details",
{action:"pnlv-triggered-ts-since-last-capi-rcvd",label:c,properties:d});_gaq.push(["_trackEvent","CRX","pnlv-triggered-ts-since-last-capi-rcvd",c]);_kmq.push(["record","pnlv-triggered-ts-since-last-capi-rcvd",d])}},5E3)}
function handleC2DM_GCM_Errors(a,b){if(-1<b.indexOf("LOGIN_REQUIRED"))_gaq.push(["_trackEvent","CRX","C2DM-Error","LOGIN_REQUIRED",1]),getLocalizedAppString({key:"error_not_logged_in"}),setBrowserActionIcon("user-not-logged-in"),createUserNotLoggedInNotification();else{if(-1<b.indexOf("DEVICE_NOT_REGISTERED")){_gaq.push(["_trackEvent","CRX","C2DM-Error","DEVICE_NOT_REG",1]);var c=getLocalizedAppString({key:"error_not_registered"})}else-1<b.indexOf("DeviceQuotaExceeded")?(_gaq.push(["_trackEvent",
"CRX","C2DM-Error","DEVICE_QUOTA_EXCEEDED",1]),c=getLocalizedAppString({key:"error_phone_quota_exceeded"})):(_gaq.push(["_trackEvent","CRX","C2DM-Error","GENERAL C2DM ERROR",1]),c=getLocalizedAppString({key:"gen_c2dm_error"})+b,_gaq.push(["_trackEvent","CRX","Specific-C2DM-Error",a+"-C2DM-ERROR",1]));alert(c)}}
function errorBroadcastGetUserInfo(){var a=NEW_COUNT_GLOBAL_NOTIF;10<NEW_COUNT_GLOBAL_NOTIF&&(a="10plus");_gaq.push(["_trackEvent","CRX-Background","Error","getUserInfo-CRX-GU72-"+a,1]);console.log("----------------");NEW_COUNT_GLOBAL_NOTIF++;2>NEW_COUNT_GLOBAL_NOTIF&&(a=determineIfNotifShouldRequireInteractionBasedOnOS({notif_options:{type:"basic",priority:2,title:getLocalizedAppString({key:"mt_connection_issue_notif_title"}),message:getLocalizedAppString({key:"mt_connection_issue_notif_content"}),
iconUrl:"../img/notifications/error_icon.png"}}),chrome.notifications.create("connection-error-GU72",a,function(a){recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:"connection-error-GU72"}});genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!1,notif_sound:!0})}));setBrowserActionIcon("cannot-connect-to-textyserver")}
function errorGetDistinctHeaders(){_gaq.push(["_trackEvent","CRX-Background","Error","getDistinctHeaders-CRX-GTHRD59",1]);if(1>NEW_COUNT_GLOBAL_NOTIF){var a=determineIfNotifShouldRequireInteractionBasedOnOS({notif_options:{type:"basic",priority:2,title:getLocalizedAppString({key:"mt_sys_issues_notif_title"}),message:getLocalizedAppString({key:"mt_sys_issues_notif_content"}),iconUrl:"../img/notifications/error_icon.png"}});chrome.notifications.create("distinct-header-error-GTHRD59",a,function(a){recordNotificationAnalyticsEvent({options:{type:"notif-created",
sub_type:"distinct-header-error-GTHRD59"}});genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!1,notif_sound:!0})})}}function ___getPhoneStatus(a){global_count_request_phone_status++;1E4>global_count_request_phone_status?a?sendOtherC2DM("get_phone_status","gcm_priority_high"):sendOtherC2DM("get_phone_status","check-phone-status-not-needed"):forceReloadCRX("Get-Phone-Status-10000-Attempt-Reached")}
function setNotifPrefValuesInLocalStorageIfNotAlreadyDone(){var a=window.localStorage,b=!1;void 0===a.notif_battery_fully_charged&&(a.notif_battery_fully_charged=1);void 0===a.notif_battery_low&&(a.notif_battery_low=1);void 0===a.global_notifications&&(a.global_notifications=1);void 0===a.message_notifications&&(a.message_notifications=1,b=!0);void 0===a.phone_app_notifications&&(a.phone_app_notifications=1);void 0===a.notif_content&&(a.notif_content=1,b=!0);void 0===a.notif_auto_dismiss&&(a.notif_auto_dismiss=
1,b=!0);void 0===a.notif_auto_dismiss_time&&(a.notif_auto_dismiss_time=600,b=!0);void 0===a.notif_sound_mode&&(a.notif_sound_mode=0);void 0===a.notif_sound_tone&&(a.notif_sound_tone="Proxima.ogg");b&&setTimeout(function(){"function"==typeof ___getUserLegacyServerSettings?___getUserLegacyServerSettings():colorConsole("___getUserLegacyServerSettings is not defined!!","red")},5E3)}
function doCRXLocalStorageSetCRXIsAlive(){var a=document.body.appendChild(document.createElement("iframe"));a.src="https://mightytext.net/prod-assets/chrome_ext_heartbeat";a.height=0;a.onload=function(){console.log("set localstorage of CRX alive via iframe")}}
function forceReloadCRX(a){a||(a="Unknown");10>Math.floor(100*Math.random())&&(_gaq.push(["_trackEvent","CRX-Background","CRX-Forced-Reload-Sample-10pct",a]),countCurrentChromeNotifsBeforeCRXRestarts({callback:function(a){"undefined"!=typeof a&&a.hasOwnProperty("num_notifs")&&_gaq.push(["_trackEvent","CRX-Background","CRX-Pre-Forced-Reload-Notif-Count-Sample-10pct",a.num_notifs.toString()])}}));setTimeout(function(){window.location.reload()},1E3)}
function countCurrentChromeNotifsBeforeCRXRestarts(a){chrome.notifications.getAll(function(b){console.info(new Date+" num chrome notifs:"+Object.keys(b).length,b);b=Object.keys(b).length;"undefined"!=typeof a&&a.hasOwnProperty("callback")&&a.callback({num_notifs:b})})}function openSignInURLInNewTab(){chrome.tabs.create({url:signInUrlCRX},function(){console.log("new tab of signInURL created")})}function checkNotifDisplaySettingsAndNotifyUser(){return!1}
function backupBrowserActionIconChecker(){chrome.browserAction.getTitle({},function(a){colorConsole("Inside of backupBrowserActionIconChecker. Current BA tooltip content: "+a,"#FF8DC6","14px");if(-1<a.indexOf("Please check your internet connection"))if(colorConsole("BA indicates user has no internet connectivity.  Confirming...","#FF8DC6","14px"),navigator.onLine)checkRegularInternetConnection(function(){forceReloadCRX("Browser-Action-Incorrect-No-Int")});else return!1;else-1<a.indexOf("Not Logged In")&&
(colorConsole("BA indicates user is not signed into MT.  Confirming that they have internet connectivity.","#FF8DC6","14px"),navigator.onLine?checkRegularInternetConnection("",function(){forceReloadCRX("Browser-Action-Incorrect-Not-Logged-In")}):forceReloadCRX("Browser-Action-Not-Logged-In-Wrong"))})}
function ___getUserLegacyServerSettings(a){$.ajax({url:baseUrl+"/usersettings?function=getUserSettings",type:"POST",dataType:"json",success:function(b){void 0!=b.usersettings.settings_list&&(b=jQuery.parseJSON(b.usersettings.settings_list.value),"undefined"!=typeof a&&a.hasOwnProperty("reminders_exp_flag_key")?(a.user_settings=b,checkIfUserShouldEnterRemindersExp(a)):portThisUsersLegacyNotificationSettingValues(b))}})}
function portThisUsersLegacyNotificationSettingValues(a){var b=a.notif_toggle_on_off,c=a.notif_content;a=a.notif_dismiss_time;var d=window.localStorage;console.log({toggle:b,privacy:c,dismiss:a});b&&"0"==b&&(d.message_notifications=0);c&&"1"==c&&(d.notif_content=0);a&&"9999"!=a&&60>parseInt(a)&&(d.notif_auto_dismiss=1,"30"==a&&(a="20"),d.notif_auto_dismiss_time=a)}
function clearAndRefetchUserContacts(a){a&&___clearJstorage(!0);clearGlobalPhoneContactNamesArray();getPhoneContactsFromServer();setTimeout(function(){getThreadsAndPopulateJStorage()},2E3)}function notifyOptionsPageOfContactRefreshResponse(a){chrome.runtime.sendMessage({refreshContactsFromPhoneC2DMSent:!0,status:a},function(a){console.log(a)})}
function clearPhoneContactNamesFromJStorage(a){$(contactsFromPhoneGlobal).each(function(a,c){var b=username_prefix_jstrg_purpose+"|PC_"+c.phoneNumClean;"contact-not-found-in-jstorage"!=$.jStorage.get(b,"contact-not-found-in-jstorage")&&$.jStorage.deleteKey(b)});a&&a()}function clearGlobalPhoneContactNamesArray(){contactsFromPhoneGlobal=[]}
function repopulatePhoneContactNamesArrayThenGetThreadsAndPopulateJStorageContactNames(){getPhoneContactsFromServer(function(){getThreadsAndPopulateJStorage()})}function setGlobalLastKnownSystemStatus(){chrome.idle.queryState(globalSystemIdleStatusThresholdInSeconds,function(a){colorConsole('Setting var globalLastKnownSystemStatus to: "'+a+'"',"purple");globalLastKnownSystemStatus=a})}chrome.idle.setDetectionInterval(globalSystemIdleStatusThresholdInSeconds);
chrome.idle.onStateChanged.addListener(function(a){"active"==a&&"locked"==globalLastKnownSystemStatus&&(clearOldLockedChromeNotificationsFromTray(),colorConsole("the system was locked, but became active","orange"));globalLastKnownSystemStatus=a;colorConsole("System status changed to: "+a+" at: "+new Date,"orange")});
function checkIfUserIsInReminderExperiment(a){"exp-flag-not-set"==$.jStorage.get("mt_reminders_experiment","exp-flag-not-set")&&___getUserLegacyServerSettings({reminders_exp_flag_key:"mt_reminders_experiment",user_info:a})}
function checkIfUserShouldEnterRemindersExp(a){var b=a.user_info,c=a.user_settings,d=a.reminders_exp_flag_key;chrome.runtime.getPlatformInfo(function(a){var e="unknown";"mac"==a.os?e="Mac":"win"==a.os&&(e="Windows");chrome.tabs.query({active:!0,currentWindow:!0},function(a){0<a.length&&(a=a[0].height,a={phone_apk_version:parseFloat(b.current_app_version),os:e,browser:"Chrome",viewport_height:a,is_pro:isAProUser,phone_lang:c.language,crx_version:manifest.version,client:"crx"},a=JSON.stringify(a),$.ajax({type:"POST",
url:baseUrl+"/bridge?function=checkIfUserIsInRemindersExp",data:{client_details:a},dataType:"json",success:function(a){console.info(a);a.hasOwnProperty("status")&&"true"==a.status&&$.jStorage.set(d,"user-in-exp")},error:function(a,b,c){console.error(new Date+" an error occurred while checking user's reminder exp status: "+b)}}))})})}
function createSuperPermissionNotif(){chrome.notifications.create("inject-into-all-tabs",{type:"basic",priority:2,title:"New: Dial a number from any website",message:"Interested in making calls from your computer?",contextMessage:"(With your android phone number)",iconUrl:"../img/48x48_MT_logo_boom_gradient_white.png",buttons:[{title:"Sure!"},{title:"Maybe Later"}]})}
function getAllCurrentPermissionsGranted(){chrome.permissions.getAll(function(a){console.info("Permissions granted as of: "+new Date,a)})}function removeWildcardHostPermission(){chrome.permissions.remove({origins:["*://*/*"]},function(a){})}chrome.permissions.contains({origins:["*://*/*"]},function(a){a&&setupOptionalWebNavListeners()});
function checkIfThisTabIsAlreadyRunningOurContentScript(a){chrome.tabs.sendMessage(activeTabID,{content_script_check:!0},function(a){console.info("in response of content script check chrome tab message",a);"undefined"==typeof a&&chrome.tabs.executeScript(activeTabID,{file:"scripts/libs/jquery-2.1.0.min.js"},function(){console.log("executed jquery");chrome.tabs.executeScript(activeTabID,{file:"scripts/common.js"},function(){console.log("inserted common.js");chrome.tabs.executeScript(activeTabID,{file:"scripts/content_script.js"},
function(){console.log("executed content_script.js")})})})})}function setupOptionalWebNavListeners(){chrome.webNavigation.onCompleted.addListener(function(a){console.info("webNavigation completed",a)});chrome.tabs.onActivated.addListener(function(a){console.info("tab activated",a)});chrome.tabs.onUpdated.addListener(function(a){console.info("tab updated",a)})}
function createLowPriorityNotification(){chrome.notifications.create("lower-priority-notif"+getRandomInt(0,100),{},function(a){console.info("low priority notif created",a)})}var acceptedOverrideLSKeys=["webapp_path_override"];
function ___setCRXAdminOverrides(a){var b=new Date+" Something went wrong. Check your syntax and try again.";if("undefined"!=typeof a&&a.hasOwnProperty("override")&&"object"==typeof a.override&&!$.isEmptyObject(a.override)){var c=!1,d="set";a.hasOwnProperty("action")&&(d=a.action);$.each(a.override,function(a,f){-1<acceptedOverrideLSKeys.indexOf(a)?("remove"==d?(localStorage.removeItem(a),b='"'+a+'" override removed!'):(localStorage.setItem(a,f),b='"'+a+'" set to "'+f+'"'),c=!0):console.error(new Date+
' Error:  Unrecognized override property: "'+a+'"')});c&&checkForAdminOverridesInLocalStorage({found_callback:function(a){"undefined"!=typeof a&&a.hasOwnProperty("override_value")&&(a=a.override_value,null!=a&&"string"==typeof a&&(console.error(a),currentProductionPath=a))}})}return b}checkForAdminOverridesInLocalStorage({found_callback:function(a){"undefined"!=typeof a&&a.hasOwnProperty("override_value")&&(a=a.override_value,null!=a&&"string"==typeof a&&(currentProductionPath=a))}});
function checkForAdminOverridesInLocalStorage(a){var b=!1;$(acceptedOverrideLSKeys).each(function(c,d){if(null!=localStorage.getItem(d)&&"webapp_path_override"==d){var e=localStorage.getItem("webapp_path_override");"undefined"!=typeof a&&a.hasOwnProperty("found_callback")&&a.found_callback({override_value:e});b=e}});return b}
function createListNotif(){chrome.notifications.create({title:"MightyText",type:"basic",message:"normal message",expandedMessage:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean porta nibh condimentum risus aliquet, quis malesuada risus aliquet. Curabitur ut pulvinar ipsum. Maecenas nec tortor in tellus convallis tristique eu id elit. Mauris sodales eget nullam.",priority:2,iconUrl:"../img/48x48_MT_logo_boom_gradient_white.png",eventTime:Date.now(),contextMessage:"7:33PM",buttons:[{title:"button #1",
iconUrl:"../img/notifications/settings.png"},{title:"button #2",iconUrl:"../img/notifications/settings.png"}]},function(a){})}
function checkInternetConnectionOutbound(a){console.log("--------Checking outbound internet connection");$.ajax({type:"GET",url:"https://ajax.googleapis.com/ajax/libs/webfont/1.3.0/webfont.js",cache:!1,dataType:"html",success:function(b){console.log("Network ping for checking js file on google server...Success");a()},error:function(){console.log("Network ping for checking js file on google server...FAILED")}})}
function getUserLocaleInfo(a){$.ajax({type:"GET",url:"https://mightytext.co:2002?function=getCountryAndCheckIfEU&client=crx",dataType:"json",timeout:5E3,success:function(a){console.info(a);"country_code"in a&&"is_eu"in a&&a.is_eu&&createCustomUpdatedTOSPPNotifWindow({user_ip_info:a})},error:function(a,c,d){console.error("ip location info error status",c)}})}
function createCustomUpdatedTOSPPNotifWindow(a){a=void 0===a?{}:a;try{userIPInfo=a.user_ip_info,createCustomPopupNotifWindow({custom_id:"tos-pp-update-prompt",url:chrome.extension.getURL("html/custom-notif.html#mode=tos-pp&is_eu="+userIPInfo.is_eu+"&country_code="+userIPInfo.country_code),on_create_cb:function(){recordTOSPPUpdateAnalyticsEvent({action:"impression"});$.jStorage.set("user-tos-pp-consent-prompt","notif-already-shown",{TTL:864E5})},keep_track_of_window:!0,height:144})}catch(b){console.error("Error occurred while creating notif window for updated tos/pp",
b)}}
function checkIfUserHasGivenConsentForLatestTOSPP(){closeAnyExistingTOSPPUpdatePopupWindows();if(null!=$.jStorage.get("user-tos-pp-consent-prompt"))return console.info("[TOS PP  Update] User has recently dismissed the tos pp consent modal. Not even going to bother checking the consent status for this user"),!1;$.ajax({type:"GET",url:baseUrl+"/userconsents?function=getLatestUserConsentsStatus&type=tos-pp",dataType:"json",timeout:1E4,xhrFields:{withCredentials:!0},success:function(a){console.info("User Consent Data Response",a);
a.ok&&!1===a.user_tos_pp_consent_given&&getUserLocaleInfo()},error:function(a,b,c){}})}function recordUserTOSPPConsent(a){a=void 0===a?{}:a;a=a.ip_info;$.ajax({type:"POST",url:baseUrl+"/userconsents?function=insertUserConsent",data:{action:"consent",client_name:"crx",type:"tos-pp",client_locale_info:a.country_code,mt_eu_assessment:a.is_eu},timeout:1E4,dataType:"json",xhrFields:{withCredentials:!0},success:function(a){console.info("User Consent Insert Data Response",a)},error:function(a,c,d){}})}
function closeAnyExistingTOSPPUpdatePopupWindows(a){try{chrome.windows.getAll({windowTypes:["popup"]},function(a){0<a.length&&a.forEach(function(a){console.info("[TOS PP] window",a);chrome.tabs.query({windowId:a.id},function(a){a.forEach(function(a){console.info("[TOS PP] tab url",a.url);-1<a.url.indexOf("custom-notif.html#mode=tos-pp")&&chrome.tabs.remove(a.id)})})})})}catch(b){console.error("Unable to query for popup type windows to check for existing ",b)}}
function recordTOSPPUpdateAnalyticsEvent(a){a=void 0===a?{action:""}:a;try{var b={updated_tos_pp_consent_client:"crx"};"ip_info"in a&&"is_eu"in a.ip_info&&(b.crx_updated_tos_pp_consent_is_eu_check=a.ip_info.is_eu.toString());_kmq.push(["record","updated-tos-pp-consent-"+a.action,b])}catch(c){console.error("Error occurred recording analytics event for TOS/PP update container",c)}};