var globalNewNotifMetadata={},globalIncomingMsgThreadNotifDetailsObj={},socket,globalHaveCalledProcessPhoneStatusThisSession=!1;
function checkWhenWasLastSuccessfulPUSH(){var a=((new Date).getTime()-webapp_crx_time_last_successful_health_check_received.getTime())/1E3;pushServiceLogger("Seconds Since LAST SUCCESSFUL INCOMING PUSH: "+roundNumber(a,2)+"secs ("+roundNumber(a/60,2)+" minutes)");300<a&&invokeHealthCheckPush();480<a?(pushServiceLogger("ALERT! has been > 8 minutes since last incoming PUSH. Will RESTART CRX in 5 seconds . . ."),window.setTimeout(function(){forceReloadCRX("Push-Socket-Error")},5E3)):pushServiceLogger("----- has NOT been > 8 minutes since last incoming PUSH -- OK")}
function invokeHealthCheckPush(){console.log(" ");console.log("------------------------------------------------ NEW POLL - HealthCheckPUSH -----------------------------------");console.log("webapp-loop at: "+Date()+" for user email -> "+google_username_currently_logged_in);body_text_to_send="CAPI_HEALTH_CHECK_FROM_CRX -- "+(new Date).getTime().toString();$.ajax({url:baseUrl+"/test?function=capi&body="+body_text_to_send+"&phone_num=123456789",type:"POST",dataType:"text",success:function(a){console.log(a);
time_last_success_mighty_ping=new Date;-1!=a.search("user not logged in")?(console.log("User is not logged in to MightyText"),setBrowserActionIcon("user-not-logged-in"),closePushSocket(),"SIGNED_IN"==push_helper_global_login_state&&(createUserNotLoggedInNotification(),push_helper_global_login_state="SIGNED_OUT")):-1!=a.search("CAPI test sent successfully")&&(setBrowserActionIcon("user-logged-in"),push_helper_global_login_state="SIGNED_IN")}})}
function determineIfNotifShouldRequireInteractionBasedOnOS(a){var b={};"undefined"!=typeof a&&"notif_options"in a&&(b=a.notif_options,"Mac"!=globalUserOS&&$.extend(b,{requireInteraction:!0}));return b}
function processIncomingPUSH(a){userIsDefaultPushServiceCapable=!0;webapp_crx_time_last_successful_health_check_received=new Date;var b=!1,d=jQuery.parseJSON(a);if(void 0!==d.new_content){var c=d.new_content;if(!(-1<c.body.search("CAPI_HEALTH_CHECK")||-1<c.body.search("USER_UPDATED_SETTINGS_IN_WEBAPP"))){if(!shouldThisPUSHTriggerANotif("message_notifications"))return!1;window.localStorage.notif_content&&"0"==window.localStorage.notif_content&&(b=!0);if(0==c.stale_notif_flag&&61!=c.inbox_outbox&&84!=
c.type&&85!=c.type){var f="",e="";a=optionalReturnSpecialEncodedString(c.body);if(10==c.type){f="";e=a;var g="SMS"}else 11==c.type?void 0!==c.mms_object_key&&(f=getLocalizedAppString({key:"pic_msg_from"})+" ",e=a,g="MMS"):20==c.type?(f=getLocalizedAppString({key:"group_msg_from"})+" ",e=a,g="GroupText"):21==c.type?(f=getLocalizedAppString({key:"group_pic_msg_from"})+" ",e=a,g="GroupPicText"):80==c.type?f=getLocalizedAppString({key:"incoming_call_from"})+" ":81==c.type&&(f=getLocalizedAppString({key:"missed_call_from"})+
" ");var h="";h=getContactNameFromCaches(c.phone_num_clean,c.phone_num);a=CRX_genericGetThumbnailFromCaches(c.phone_num_clean,c.phone_num);var k=getRandomInt(0,10);"undefined"!=typeof g&&0===k&&_kmq.push(["record","Incoming-Message-10pct",{Type:g,Client:"CRX",incoming_message_crx_version:manifest.version}]);b&&void 0==c.enlargeMMSMode&&(e=getLocalizedAppString({key:"click_to_see_message"})+"...");window.localStorage.notif_auto_dismiss&&"1"==window.localStorage.notif_auto_dismiss&&(notif_dismissal_time=
1E3*parseInt(window.localStorage.notif_auto_dismiss_time));"is_snoozed"in c||$.extend(c,{is_snoozed:!1});globalNewNotifMetadata[c.id]=c;g=f+h;f=e;h=getLocalizedAppString({key:"reply"});if(20==c.type||21==c.type)a=getSanitizedPhoneNumberRemoveHyphensParenthesisSpaces(c.content_author,!0),g=getContactNameFromCaches(a,c.content_author),a=CRX_genericGetThumbnailFromCaches(a,c.content_author),g=getLocalizedAppString({key:"group_mms_from"})+" "+g,f=getContactNameFromCaches("N/A",c.phone_num),f=e+"\r\n\r\n("+
f+")",h=getLocalizedAppString({key:"reply_to_group"});e=getLocalizedAppString({key:"remind_me_in"});k="../img/notifications/teal_alarm_bell_snooze-48.png";if(10==c.type||20==c.type){var p=$.jStorage.get("mt_reminders_experiment","exp-flag-not-set"),l={msg_type:c.type};"exp-flag-not-set"!=p?(e=getLocalizedAppString({key:"remind_me_in_new"}),k="../img/notifications/crx-reminder-inc-msg-snooze6.png",l.new_reminder_btn=!0):l.new_reminder_btn=!1;c.hasOwnProperty("msg_reminder")||recordIncomingMessageNotifImpression(l)}if(11==
c.type||21==c.type)b||(a=baseUrl+"/imageserve?function=fetchFile&id="+c.id),e=getLocalizedAppString({key:"view_full_pic"}),k="../img/notifications/teal_photoview_32.png";20!=c.type&&11!=c.type&&21!=c.type||removeInitialMMSWakeupChromeNotifForThisContentAuthor({content_author:getSanitizedPhoneNumberRemoveHyphensParenthesisSpaces(c.content_author,!0)});if(80==c.type||81==c.type)h=getLocalizedAppString({key:"send_text_msg"}),80==c.type?(e=getLocalizedAppString({key:"decline_on_phone"}),k="../img/notifications/end_call_notif.png"):
c.hasOwnProperty("missed_call_reminder")?f=c.body:81==c.type&&recordIncomingMessageNotifImpression({msg_type:c.type,new_reminder_btn:!1});var m={type:"basic",title:g,message:f,priority:2,eventTime:Date.now(),isClickable:!0,iconUrl:a,buttons:[{title:h,iconUrl:"../img/notifications/teal-new-reply-btn-icon.png"},{title:e,iconUrl:k}]};80!=c.type&&81!=c.type&&"Mac"!=globalUserOS&&(m.requireInteraction=!0);"Windows"==BrowserDetect.OS&&(m.contextMessage=buildIncomingMessageContextMessage({timestamp:c.ts_server}));
window.localStorage.hasOwnProperty("notif_auto_dismiss");if(void 0!==c.enlargeMMSMode)b=determineIfNotifShouldRequireInteractionBasedOnOS({notif_options:{type:"image",title:g,message:f,iconUrl:a,priority:2,eventTime:Date.now(),imageUrl:baseUrl+"/imageserve?function=fetchFile&id="+c.id,buttons:[{title:h,iconUrl:"../img/notifications/teal-new-reply-btn-icon.png"}]}}),"Windows"==BrowserDetect.OS&&(m.contextMessage=buildIncomingMessageContextMessage({timestamp:c.ts_server})),chrome.notifications.create(c.id+
"-picture",b,function(a){recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:"enlarged-pic"}});genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!1,notif_sound:!1});getCurrentIdleStateAndStoreThisNotifIDInJstorage(a)});else{var q=c.id,r=$.extend({},m,{id:q,msg_id:c.id,is_snoozed:c.is_snoozed});checkIfUserAlreadyHasAnOpenQRWindowWithThisContact({msg:c,not_active_in_qr_callback:function(){checkIfThereIsAnExistingChromeNotifForThisConv({notif_details:r,create_notif_cb:function(){chrome.notifications.create(q,
m,function(a){recordAnalyticsForIncomingMsgNotifCreation({origin:"new_chrome_notif_created",msg_type:c.type});colorConsole("Just created a Incoming Message Notif at: "+new Date+"with the ID "+a,"green");recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:c.type}});genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!0,notif_sound:!0})})},update_notif_cb:function(){recordAnalyticsForIncomingMsgNotifCreation({origin:"incoming_sms_batched_in_chrome_notif",msg_type:c.type})}})},
active_in_qr_callback:function(){recordAnalyticsForIncomingMsgNotifCreation({origin:"user_active_in_qr_window_with_this_contact",msg_type:c.type})}})}}}}else if(void 0!==d.phone_status){a=d.phone_status;e="";b=Math.floor(a.battery_level);g=a.battery_is_charging;f=((new Date).getTime()-parseInt($.jStorage.get("ts_last_battery_alert_notif_shown",0)))/1E3;chrome.runtime.sendMessage({phoneStatus:a},function(a){console.log(a)});processPhoneStatus(a);console.log("Num seconds since last battery alert notification on this CRX: "+
f);$.jStorage.set("latest_phone_status",a,{TTL:36E4});h=shouldThisPUSHTriggerANotif("notif_battery_fully_charged");k=shouldThisPUSHTriggerANotif("notif_battery_low");if("true"==g&&0!=h)return console.log("phone is charging - no notification to consider, unless battery is at 100%"),99<b&&3600<f&&(void 0!==a.ts_phone_utc&&(a=a.ts_phone_utc/1E3,a=moment.unix(a).format("h:mm a"),e="(as of "+a+")"),b={type:"basic",title:getLocalizedAppString({key:"full_batt_notif_title"}),message:getLocalizedAppString({key:"full_batt_notif_content"})+
".\r\n\r\n\r\n"+e,contextMessage:"MightyText",priority:2,eventTime:Date.now(),iconUrl:"../img/notifications/battery-full.png",buttons:[{title:getLocalizedAppString({key:"bat_notif_settings"}),iconUrl:"../img/notifications/settings.png"}]},a=(new Date).getTime().toString(),$.jStorage.set("ts_last_battery_alert_notif_shown",a),a=randomStringGenerate(4),chrome.notifications.create("notif-battery-full-"+a,b,function(a){colorConsole("Just created a Batt Full at: "+new Date+"with the ID "+a,"green");recordNotificationAnalyticsEvent({options:{type:"notif-created",
sub_type:"batt-full"}});genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!1,notif_sound:!0})})),!1;"false"==g&&0!=k&&2700<f&&(10>=b||12==b||14==b||16==b)&&(void 0!==a.ts_phone_utc&&(a=a.ts_phone_utc/1E3,a=moment.unix(a).format("h:mm a"),e="(as of "+a+")"),b={type:"basic",title:getLocalizedAppString({key:"low_bat_notif_title"}),message:getLocalizedAppString({key:"low_bat_notif_content"})+": "+b+"%  "+e,contextMessage:"MightyText",eventTime:Date.now(),iconUrl:"../img/notifications/low_battery_48.png",
buttons:[{title:getLocalizedAppString({key:"bat_notif_settings"}),iconUrl:"../img/notifications/settings.png"}]},a=(new Date).getTime().toString(),$.jStorage.set("ts_last_battery_alert_notif_shown",a),a=randomStringGenerate(4),chrome.notifications.create("notif-battery-low-"+a,b,function(a){colorConsole("Just created a Batt Low at: "+new Date+"with the ID "+a,"green");recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:"batt-low"}});genericChromeNotifCreateCallback({notif_id:a,
auto_dismiss:!1,notif_sound:!0})}))}else if(void 0!==d.ack_processed)b=d.ack_processed,0>b.status_route&&(console.log("message failed!"),console.log(b),a=b.body,e=b.phone_num_clean,e=getContactNameFromCaches(e,b.phone_num),globalNewNotifMetadata[b.id]=b,a=getLocalizedAppString({key:"msg_send_failure"}).replace("%msg_body%",a).replace("%contact_name%",e),a=determineIfNotifShouldRequireInteractionBasedOnOS({notif_options:{type:"basic",title:"Warning",message:a,contextMessage:buildIncomingMessageContextMessage(),
eventTime:Date.now(),iconUrl:"../img/notifications/error_icon.png"}}),b="message-send-failure-"+b.id,console.error("msg send fail notif",a),chrome.notifications.create(b,a,function(a){colorConsole("Just created a Message Failed Notif at: "+new Date+"with the ID "+a,"green");recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:"msg-send-failure"}});genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!1,notif_sound:!0})}));else if(void 0!==d.device_notification)b=d.device_notification,
a=String(b.ts_post),console.log(b),deviceNotifManagerArray[a]={},deviceNotifManagerArray[a].package_name=b.package_name,deviceNotifManagerArray[a].device_id=b.device_id,deviceNotifManagerArray[a].id=b.id,deviceNotifManagerArray[a].app_name=b.app_name,deviceNotifManagerArray[a].original_object=b,0!=shouldThisPUSHTriggerANotif("phone_app_notifications")&&getImageForNotifFromDevice(b);else if(void 0!==d.end_call_info)b=d.end_call_info,1E4<(new Date).getTime()-b.ts_ended_utc||(a={type:"basic",message:"",
contextMessage:buildIncomingMessageContextMessage(),priority:2,eventTime:Date.now(),iconUrl:"../img/notifications/end_call_notif.png"},1==b.status?a.title=getLocalizedAppString({key:"call_declined"}):0==b.status?a.title=getLocalizedAppString({key:"call_decline_error"}):-99==b.status&&(a.title=getLocalizedAppString({key:"call_in_progress"}),a.iconUrl="../img/notifications/call_in_progress.png"),chrome.notifications.create("end-call-status"+b.ts_ended_utc,a,function(a){recordNotificationAnalyticsEvent({options:{type:"notif-created",
sub_type:"end-call-confirm"}});genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!1,notif_sound:!1})}));else if(void 0!==d.client_changed_login_state)console.log(d.client_changed_login_state),setTimeout(function(){checkUserLoginStatusAfterPUSHNotifyLogout()},1E3);else if(void 0!=d.contact_photo_refreshed_from_phone)b=d.contact_photo_refreshed_from_phone.phone_num,e=getSanitizedPhoneNumberRemoveHyphensParenthesisSpaces(b,"do_not_zeropad"),getContactImageFromCloudAndSetJStorage(b,e);else if(void 0!==
d.generic_notification){var n={title:"MightyText",type:"basic",priority:2,iconUrl:"../img/48x48_MT_logo_boom_gradient_white.png"};$(d.generic_notification).each(function(a,b){var c=(new Date).getTime();b.hasOwnProperty("subject")&&(b.hasOwnProperty("type")&&"-1"==b.type?(n.title=b.subject,-1<b.additional_info.indexOf("show-pro-button")&&(c+="-msg-send-quota")):n.title=b.subject);var d=b.body.replace(/(< ?\/?br ?\/?>)+/,"\n");n.message=d;b.hasOwnProperty("additional_info")&&-1<b.additional_info.indexOf("show-pro-button")&&
(n.buttons=[{title:getLocalizedAppString({key:"go_pro"}),iconUrl:"../img/notifications/go_pro.png"}]);chrome.notifications.create("generic-notif-"+c,n,function(a){try{var c="generic-notif";"-1"==b.type&&"show-pro-button"==b.additionalInfo&&(c="send-limit-notif");recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:c}})}catch(t){console.error("[NOTIF ANALYTICS] Unable to record notif create event for generic notif",t)}genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!1,
notif_sound:!0})})})}else if(d["contacts-names-update-complete"])createNotificationForLatestContactsRefreshed(),clearPhoneContactNamesFromJStorage(function(){clearGlobalPhoneContactNamesArray();repopulatePhoneContactNamesArrayThenGetThreadsAndPopulateJStorageContactNames()});else if(d.hasOwnProperty("reminder_id")){b=shouldThisPUSHTriggerANotif("reminder_notif");if(!b)return!1;b=d.name;a=d.description;e=d.token_id;g={type:"basic",title:b,message:"",contextMessage:buildIncomingMessageContextMessage(),
priority:2,iconUrl:"../img/notifications/reminder-crx-notif.png",buttons:[{title:getLocalizedAppString({key:"reminder_snooze"}),iconUrl:"../img/notifications/crx-reminder-snooze.png"}]};50<b.length&&(g.title="Reminder",g.message=b);0<g.length&&(g.contextMessage=a);chrome.notifications.create("reminder-"+e,g,function(a){genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!1,notif_sound:!0});acknowledgeThatThisReminderWasCreated(d);globalNewNotifMetadata[a]=d})}else if(d.hasOwnProperty("event_update_notify")){b=
shouldThisPUSHTriggerANotif("event_update_notify");if(!b)return!1;handleScheduledEventPUSH({scheduled_msg_capi_info:d.event_update_notify})}else if(d.hasOwnProperty("media_uploaded")){b=shouldThisPUSHTriggerANotif("media_uploaded");if(!b)return!1;displayMediaUploadedNotif({media_uploaded_info:d.media_uploaded})}else console.log("unknown incoming CAPI content")}
function triggerWebNotification(a){a=void 0===a?{}:a;var b=new Notification(a.title,{body:a.body,icon:a.icon,tag:a.id});"on_create_options"in a&&"object"==typeof a.on_create_options&&(notifOncreateOptions=a.on_create_options,genericChromeNotifCreateCallback({notif_id:a.id,auto_dismiss:notifOncreateOptions.auto_dismiss,notif_sound:notifOncreateOptions.notif_sound,optional_notif_ref:b}));console.info("[WEB NOTIFICATIONS] Notif created");b.onclick=function(a){a.preventDefault();b.close();console.info("[WEB NOTIFICATIONS] notif clicked",
a);commonNotificationOnClickHandler({id:a.target.tag}.id)};b.onclose=function(a){console.info("[WEB NOTIFICATIONS] notif closed",a);commonNotificationOnRemoveHandler(a.target.tag,!0)}}
function checkIfUserAlreadyHasAnOpenQRWindowWithThisContact(a){"undefined"!=typeof a&&a.hasOwnProperty("msg")&&"object"==typeof a.msg&&a.hasOwnProperty("not_active_in_qr_callback")&&"function"==typeof a.not_active_in_qr_callback&&("mms_wakeup"in a.msg&&!0===a.msg.mms_wakeup&&11!=a.msg.type?a.not_active_in_qr_callback():chrome.windows.getLastFocused({populate:!0},function(b){var d=!0;if(!chrome.runtime.lastError&&b.hasOwnProperty("type")&&"popup"==b.type&&b.hasOwnProperty("tabs")&&"object"==typeof b.tabs&&
"focused"in b&&!0===b.focused){var c=a.msg.phone_num_clean;$(b.tabs).each(function(a,b){if(b.hasOwnProperty("url")){console.info("url found! "+b.url);var e=$.deparam(b.url);console.info("hash params obj",e);e.hasOwnProperty("thread_id")&&(console.info("thread ID found! "+e.thread_id),e.thread_id==c&&(console.info("thread ID's match! don't create a chrome notif!"),d=!1))}})}0!=d?a.not_active_in_qr_callback():"active_in_qr_callback"in a&&a.active_in_qr_callback()}))}
function populateGlobalThreadDetailsObj(a){if("undefined"!=typeof a&&a.hasOwnProperty("notif")){var b=a.notif,d=b.phone_num_clean;if(!(d in globalIncomingMsgThreadNotifDetailsObj))$.extend(b,{num_msgs_grouped_in_notif:1,msg_ids_of_grouped_msgs:[b.id]}),globalIncomingMsgThreadNotifDetailsObj[d]=[b];else if("new_notif_created"in a||"msg_type"in b&&checkIfPUSHIsPicType({type:b.msg_type}))$.extend(b,{num_msgs_grouped_in_notif:1,msg_ids_of_grouped_msgs:[b.id]}),globalIncomingMsgThreadNotifDetailsObj[d].push(b);
else if(d in globalIncomingMsgThreadNotifDetailsObj){a=globalIncomingMsgThreadNotifDetailsObj[d][globalIncomingMsgThreadNotifDetailsObj[d].length-1];var c=a.num_msgs_grouped_in_notif,f=a.msg_ids_of_grouped_msgs;d=a.message+("\n"+b.message);newNumMsgsGrouped=c+1;f.push(b.id);globalNewNotifMetadata[a.id].body=d;$.extend(a,{message:d,ts_notif_updated:b.ts_notif_updated,num_msgs_grouped_in_notif:newNumMsgsGrouped,msg_ids_of_grouped_msgs:f})}}}
function checkIfPUSHIsPicType(a){var b=!1;"undefined"!=typeof a&&"type"in a&&-1<[11,21].indexOf(a.type)&&(b=!0);return b}function checkIfPUSHIsCallType(a){var b=!1;"undefined"!=typeof a&&"type"in a&&-1<[80,81,83,84,85].indexOf(a.type)&&(b=!0);return b}
function removeThreadFromGlobalThreadDetailsObj(a){if("undefined"!=typeof a&&"phone_num_clean"in a&&"msg_id"in a){var b=a.phone_num_clean;b in globalIncomingMsgThreadNotifDetailsObj&&$(globalIncomingMsgThreadNotifDetailsObj[b]).each(function(d,c){"msg_id"in c&&c.msg_id==a.msg_id&&(globalIncomingMsgThreadNotifDetailsObj[b].splice(d,1),0===globalIncomingMsgThreadNotifDetailsObj[b].length&&delete globalIncomingMsgThreadNotifDetailsObj[b])})}}
function OLD_processHealthCheckInboundCAPI(){webapp_crx_time_last_successful_health_check_received=new Date}
function OLD_getRefreshedContactPhotoAndSaveToDom(a,b){colorConsole("inside of getRefreshedContactPhotoAndSaveToDom.  We are getting a new contact photo for the full num: "+b);var d="phone_num_clean="+a+"&phone_num_full="+encodeURIComponent(b);$.ajax({url:baseUrl+"/phonecontact?function=getPhoneContactPhotos",data:d,type:"POST",dataType:"json",success:function(b){$.jStorage.set(username_prefix_jstrg_purpose+"|PH_PIC_"+a,{contactThumbnailBinary:b.phone_contact_photo_status},{TTL:12096E5})},error:function(a){}})}
function acknowledgeThatThisReminderWasCreated(a){$.ajax({url:a.callback_url,type:"POST",data:{action:"delivered",token_id:a.token_id},dataType:"json",success:function(a){console.info(a)},complete:function(a,d){console.info("request to update complete! status: "+d)}})}
function recordIncomingMessageNotifImpression(a){if("undefined"!=typeof a&&a.hasOwnProperty("new_reminder_btn")){var b="-Legacy";0!=a.new_reminder_btn&&(b="-New-Reminder-Btn");10>getRandomInt(0,100)&&_kmq.push(["record","Incoming-Message-Notif-Shown"+b+"-10-PCT-Sample",{incoming_msg_notif_type:a.msg_type}])}}
function processPhoneStatus(a){if(globalHaveCalledProcessPhoneStatusThisSession)return!1;globalHaveCalledProcessPhoneStatusThisSession=!0;a.android_version&&(Intercom("update",{android_version:a.android_version}),5>getRandomInt(0,100)&&_gaq.push(["_trackEvent","Tracker","Android-Version-5pct-Sample",a.android_version]));if(a.android_version&&0==a.android_version.indexOf("4.4")||0==a.android_version.indexOf("4.3")||0==a.android_version.indexOf("5.0")||0==a.android_version.indexOf("5.1"))$.jStorage.set("android_4.3_or_higher",
a.android_version),a.notif_listen_enabled&&(5>getRandomInt(0,100)&&_gaq.push(["_trackEvent","Tracker","Notif-Listen-Enabled-5pct-Sample",a.notif_listen_enabled]),"1"==a.notif_listen_enabled&&$.jStorage.set("notif_listen_on","1",{TTL:12096E5}))}
function CRX_genericGetThumbnailFromCaches(a,b){var d="../img/notifications/silhouette.jpg",c=$.jStorage.get(username_prefix_jstrg_purpose+"|PH_PIC_"+a,"no-jstorage-val-found");"no-jstorage-val-found"==c?getContactImageFromCloudAndSetJStorage(b,a):"NO_PHOTO"!=c.contactThumbnailBinary&&2<c.contactThumbnailBinary.length&&(d="data:image/jpeg;base64,"+c.contactThumbnailBinary);return d}
function handleScheduledEventPUSH(a){if("undefined"!=typeof a&&a.hasOwnProperty("scheduled_msg_capi_info")&&a.scheduled_msg_capi_info.hasOwnProperty("status")&&710===a.scheduled_msg_capi_info.status){var b=a.scheduled_msg_capi_info.ref_id;$.ajax({type:"POST",url:baseUrl+"/content?function=getMessageDetail",data:"id="+b,dataType:"json",timeout:8E3,success:function(d){console.info("Sent Scheduled Message Details ",d);d.hasOwnProperty("message")?displayScheduledMessageNotif({scheduled_msg_info:d.message}):
console.error(new Date+" Could not find message details for ID: "+b," Full message details",a)},error:function(a,b,f){console.log("error in handleScheduledEventPUSH:");console.log(a);console.log(b);console.log(f)}})}}
function dismissAnyNotifsFromThisConversation(a){if("undefined"!=typeof a&&a.hasOwnProperty("msg_details")){var b=a.msg_details;$.each(globalNewNotifMetadata,function(a,c){b.phone_num_clean==c.phone_num_clean&&chrome.notifications.clear(c.id,function(a){a&&markSingleMessageReadOnPhone(c.body,c.phone_num_clean)})})}}function getAllNotifsDetails(){chrome.notifications.getAll(function(a){console.info(a)})}
function checkIfThereIsAnExistingChromeNotifForThisConv(a){if("undefined"!=typeof a&&"notif_details"in a&&"create_notif_cb"in a&&"function"==typeof a.create_notif_cb){var b=a.notif_details,d=globalNewNotifMetadata[a.notif_details.msg_id],c=d.phone_num_clean;$.extend(b,{phone_num_clean:c,msg_type:d.type});checkIfPUSHIsPicType({type:b.msg_type})||checkIfPUSHIsCallType({type:b.msg_type})||"Mac"==globalUserOS?(populateGlobalThreadDetailsObj({notif:b}),a.create_notif_cb()):chrome.notifications.getAll(function(f){var e=
(new Date).getTime(),g={notif:$.extend(b,{ts_notif_updated:e})},h="",k=!1,p=0,l;$.each(f,function(a,d){if(a in globalNewNotifMetadata&&globalNewNotifMetadata[a].phone_num_clean==c){var e=globalIncomingMsgThreadNotifDetailsObj[c][globalIncomingMsgThreadNotifDetailsObj[c].length-1];checkIfPUSHIsPicType({type:e.msg_type})||checkIfPUSHIsCallType({type:e.msg_type})?g.new_notif_created=!0:(h=e.message+"\n"+b.message,"notif_content"in localStorage&&"0"==localStorage.getItem("notif_content")&&(h=getLocalizedAppString({key:"click_to_see_n_messages",
placeholders:[e.num_msgs_grouped_in_notif+1]})),l=e.msg_id,p=e.ts_notif_updated,k=!0)}});!0===k?checkIfMsgBodyIsTooLongToFitInSingleNotif({msg_body:h,notif_title:b.title})&&checkIfItsBeenToLongSinceVisibleNotifHasBeenUpdated({current:e,past:p})&&!1===globalNewNotifMetadata[l].is_snoozed?chrome.notifications.update(l,{message:h,contextMessage:buildIncomingMessageContextMessage({timestamp:d.ts_server})},function(b){"update_notif_cb"in a&&a.update_notif_cb()}):(g.new_notif_created=!0,a.create_notif_cb()):
a.create_notif_cb();populateGlobalThreadDetailsObj(g)})}}function checkIfMsgBodyIsTooLongToFitInSingleNotif(a){var b=!1;if("undefined"!=typeof a&&"msg_body"in a&&"notif_title"in a){var d=a.notif_title;a=a.msg_body.split(new RegExp(/\n/g));var c=180,f=0,e=c/5;if(30<d.length||d.match(/\n/g))c*=.6;$(a).each(function(a,b){f=b.length<=e?f+e:f+Math.ceil(b.length/e)*e});f<=c&&(b=!0)}return b}
function checkIfItsBeenToLongSinceVisibleNotifHasBeenUpdated(a){var b=!1;if("undefined"!=typeof a&&"current"in a&&"past"in a){var d=moment(a.current);a=moment(a.past).add(2,"minutes");d.isBefore(a)&&(b=!0)}return b}function removeInitialMMSWakeupChromeNotifForThisContentAuthor(a){"undefined"!=typeof a&&a.hasOwnProperty("content_author")&&chrome.notifications.clear("incoming_mms_wakeup-"+a.content_author)}
function recordAnalyticsForIncomingMsgNotifCreation(a){"undefined"!=typeof a&&"origin"in a&&"msg_type"in a&&10>getRandomInt(0,100)&&_kmq.push(["record","Incoming-Msg-Notif-Result-10-Pct-Sample",{incoming_msg_resulting_action:a.origin,incoming_msg_type:a.msg_type}])};