var customNotifWindowIDArray=[];
chrome.notifications.onButtonClicked.addListener(function(b,c){if("Windows"==BrowserDetect.OS&&"-1"==c)commonNotificationOnClickHandler(b);else{if(-1<b.indexOf("new_media_uploaded")){var d="https://mightytext.net/"+currentProductionPath+"#mode=media";chrome.notifications.clear(b);chrome.tabs.create({url:d},function(b){console.log(b)});recordNotificationAnalyticsEvent({options:{type:"notif-btn-click",sub_type:"media-uploaded"}});return!1}if(-1<b.indexOf("generic-notif-"))d="https://mightytext.net/"+
currentProductionPath+"#promo=true",b.indexOf("-msg-send-quota")&&(d+="&feature-id=crx-msg-send-quota",recordNotificationAnalyticsEvent({options:{type:"notif-btn-click",sub_type:"send-limit"}})),chrome.notifications.clear(b),chrome.tabs.create({url:d},function(b){console.log(b)});else if(-1<b.indexOf("reminder"))0===c&&(chrome.notifications.clear(b),createReminderNotification({notif_id:b}));else if(0==b.indexOf("notif-battery-")){try{d=-1<b.indexOf("full")?"batt-full":"batt-low",recordNotificationAnalyticsEvent({options:{type:"notif-btn-click",
sub_type:d}})}catch(h){console.error("[NOTIF ANALYTICS] Unable to record notif btn click event for batt notifs",h)}chrome.notifications.clear(b);handleBatteryNotif(c)}else{if(-1<b.indexOf("device-notification-")){var e=b.replace("device-notification-","");d=deviceNotifManagerArray[e].package_name;var f=deviceNotifManagerArray[e].id,k="null";void 0!=deviceNotifManagerArray[e].original_object.tag&&(k=deviceNotifManagerArray[e].original_object.tag);0==c?(dismissNotif(d,k,f),_gaq.push(["_trackEvent",
"CRX","Device-Notif-Click-Option","dismiss-this-notif"]),"k"==google_username_currently_logged_in.charAt(0)&&_kmq.push(["record","Device-Notif-Click-Option-Letter-K",{"Package-Name":d,Client:"CRX",Action:"dismiss-this-notif"}])):1==c&&(f="../html/phone_notifs_options.html#notif_object_key="+e,createCustomPopupNotifWindow({url:f}),createAdditionPhoneNotifOptionsWindow(f,d),_gaq.push(["_trackEvent","CRX","Additional-Device-Notif-Invoke",d]),"k"==google_username_currently_logged_in.charAt(0)&&_kmq.push(["record",
"Additional-Device-Notif-Invoke-Letter-K",{"Package-Name":d,Client:"CRX"}]),e in deviceNotifManagerArray&&(deviceNotifManagerArray[e].do_not_delete_on_close_need_for_addit_window=!0));recordNotificationAnalyticsEvent({options:{type:"notif-btn-click",sub_type:"phone-app-notif",count_in_session:c}});chrome.notifications.clear(b,function(d){console.log({notif_cleared:d,notif_cleared_id:b,before_splice:deviceNotifManagerArray});0==c&&delete deviceNotifManagerArray[e];console.log({post_splice:deviceNotifManagerArray})});
return!1}d=globalNewNotifMetadata.hasOwnProperty(b)?globalNewNotifMetadata[b].type:"unknown";0==c?(_gaq.push(["_trackEvent","CRX-Background","Notif-Click","Reply-Button-Action"]),recordNotificationAnalyticsEvent({options:{type:"notif-btn-click",sub_type:d,count_in_session:c}}),commonActionsReplyToNotif(b)):1==c&&(recordNotificationAnalyticsEvent({options:{type:"notif-btn-click",sub_type:d,count_in_session:c}}),chrome.notifications.clear(b,function(c){c&&(10==globalNewNotifMetadata[b].type||20==globalNewNotifMetadata[b].type?
"exp-flag-not-set"!=$.jStorage.get("mt_reminders_experiment","exp-flag-not-set")?createReminderNotification({mode:"incoming-msg-snooze",notif_id:b}):legacyIncomingMsgSnooze({notif_id:b}):11==globalNewNotifMetadata[b].type||21==globalNewNotifMetadata[b].type?(invokeEnlargedMMSPictureMessageInNotif(b),_gaq.push(["_trackEvent","CRX-Background","Notif-Click","MMS-Picture-Enlarge-Button-Action"])):80==globalNewNotifMetadata[b].type?sendOtherC2DM("end_call","not-needed"):81==globalNewNotifMetadata[b].type&&
legacyIncomingMsgSnooze({notif_id:b}))}))}}});
function commonNotificationOnClickHandler(b){-1<b.indexOf("msg-send-quota")&&(chrome.notifications.clear(b,function(b){}),chrome.tabs.create({url:"https://mightytext.net/send-limit-oct-2015"},function(){}),recordNotificationAnalyticsEvent({options:{type:"notif-click",sub_type:"send-limit"}}));if(!(-1<b.indexOf("reminder"))){if("user_logged_in"==b||-1<b.indexOf("housead"))return!1;if(-1<b.indexOf("user_disabled_notifs"))chrome.tabs.create({url:"../html/options.html"},function(){console.log("created tab opening MT settings")}),
chrome.notifications.clear(b,function(c){console.log("crx update notif: "+b+" cleared?: "+c)});else if(-1<b.indexOf("message-send-failure")){var c=b.replace("message-send-failure-",""),d=globalNewNotifMetadata[c].phone_num_clean;checkIfThereIsAlreadyAQuickReplyForThisThread("https://mightytext.net/"+currentProductionPath+"/#mode=quick&msgid="+c+("&thread_id="+d),d);recordNotificationAnalyticsEvent({options:{type:"notif-click",sub_type:"msg-send-failure"}})}else if("user_not_logged_in"==b)chrome.notifications.clear(b),
recordNotificationAnalyticsEvent({options:{type:"notif-click",sub_type:"user-not-logged-in"}}),openSignInURLInNewTab();else if("user-install-android-app"==b)recordNotificationAnalyticsEvent({options:{type:"notif-click",sub_type:b}}),window.open("http://mightytext.net/install"),setAutoRemoveTimeOutForThisNotif(b),chrome.notifications.clear(b);else if("inject-into-all-tabs"==b)chrome.permissions.request({origins:["*://*/*"],permissions:["webNavigation"]},function(b){b&&setupOptionalWebNavListeners()});
else{if("news_notif_15.0"==b)return chrome.tabs.create({url:"http://mightytext.net/crx-v15-updates"},function(){console.log("created tab opening MT blog")}),chrome.notifications.clear(b,function(c){console.log("crx update notif: "+b+" cleared?: "+c)}),_gaq.push(["_trackEvent","CRX",b,"Click"]),!1;c="unknown";globalNewNotifMetadata.hasOwnProperty(b)&&(c=globalNewNotifMetadata[b].type);-1<b.indexOf("-picture")||81==c||80==c||(recordNotificationAnalyticsEvent({options:{type:"notif-click",sub_type:"unknown"!=
c?c:b}}),commonActionsReplyToNotif(b),_gaq.push(["_trackEvent","CRX-Background","Notif-Click","Reply-Click-On-Notif-Itself"]))}}}chrome.notifications.onClicked.addListener(commonNotificationOnClickHandler);
function commonNotificationOnRemoveHandler(b,c){$.jStorage.deleteKey("locked-notif-"+b);if(-1<b.indexOf("-picture"))recordNotificationAnalyticsEvent({options:{type:"notif-closed",sub_type:"enlarged-pic"}});else if(0==b.indexOf("notif-battery-"))try{var d=-1<b.indexOf("full")?"batt-full":"batt-low";recordNotificationAnalyticsEvent({options:{type:"notif-closed",sub_type:d}})}catch(e){console.error("[NOTIF ANALYTICS] Unable to record notif close event for batt notifs",e)}else if(0==b.indexOf("device-notification-"))d=
b.replace("device-notification-",""),c&&d in deviceNotifManagerArray&&!("do_not_delete_on_close_need_for_addit_window"in deviceNotifManagerArray[d])&&delete deviceNotifManagerArray[d],recordNotificationAnalyticsEvent({options:{type:"notif-closed",sub_type:"phone-app-notif"}});else if(globalNewNotifMetadata.hasOwnProperty(b)){c&&markSingleMessageReadOnPhone(globalNewNotifMetadata[b].body,globalNewNotifMetadata[b].phone_num_clean);removeThreadFromGlobalThreadDetailsObj({phone_num_clean:globalNewNotifMetadata[b].phone_num_clean,
msg_id:b});try{recordNotificationAnalyticsEvent({options:{type:"notif-closed",sub_type:globalNewNotifMetadata[b].type}})}catch(e){console.error("[NOTIF ANALYTICS] Error occurred while recording analytics on notif closed",e)}}else d=b,-1<b.indexOf("message-send-failure")?d="msg-send-failure":-1<b.indexOf("end-call-status")?d="end-call-confirm":-1<b.indexOf("msg-send-quota")?d="send-limit":-1<b.indexOf("generic-notif")?d="generic-notif":"user_not_logged_in"==b?d="user-not-logged-in":"latest-contacts-refreshed-from-phone"==
b?d="contacts-refreshed":-1<b.indexOf("scheduled-msg-sent")?d="scheduled-msg-sent":-1<b.indexOf("new_media_uploaded")&&(d="media-uploaded"),recordNotificationAnalyticsEvent({options:{type:"notif-closed",sub_type:d}})}chrome.notifications.onClosed.addListener(commonNotificationOnRemoveHandler);
chrome.windows.onRemoved.addListener(function(b){console.info("Removed window id",b);b=checkIfRemovedWindowWasACustomNotifWindow(b);0!=b&&"tos-pp-update-prompt"==b[0].custom_mt_id_str&&(console.info("[TOS PP] tos pp consent window removed!"),recordTOSPPUpdateAnalyticsEvent({action:"remove"}),$.jStorage.set("user-tos-pp-consent-prompt","user-dismissed",{TTL:1728E5}))});
function checkIfRemovedWindowWasACustomNotifWindow(b){var c=!1;try{0<customNotifWindowIDArray.length&&customNotifWindowIDArray.forEach(function(d){d.id===b&&(console.info("[REMOVED WINDOW CHECK] Window to keep track of ",d),c=customNotifWindowIDArray.splice(customNotifWindowIDArray.indexOf(d),1),console.info("[REMOVED WINDOW CHECK] Final custom notif window array",c))})}catch(d){console.error("Unable to determine which window ",d)}return c}
function createReminderNotification(b){if("undefined"!=typeof b&&b.hasOwnProperty("notif_id")){var c=globalNewNotifMetadata[b.notif_id],d="snooze";b.hasOwnProperty("mode")&&(d=b.mode);b=remindersAppUrl+"#mode="+d;"snooze"==d?b+="&token_id="+c.token_id+"&cb_url="+c.callback_url+"&name="+c.name:"incoming-msg-snooze"==d&&(b+=buildRemindersAppIncomingSMSSnoozeURLParams({message:c}),markSingleMessageReadOnPhone(c.body,c.phone_num_clean));c=260;var e=333;"incoming-msg-snooze"==d&&(d=window.navigator.appVersion,
c=557,e=404,-1<d.indexOf("Macintosh")&&(c=540,e=389));chrome.windows.create({url:b,left:screen.width-(c+7),top:7,width:c,height:e,focused:!0,type:"popup"},function(b){console.log("reminder window created!");console.log(b)})}}
function getLatestMessageDetailsForThisNotif(b){var c={};"undefined"!=typeof b&&"notif_id"in b&&(b=b.notif_id,b in globalNewNotifMetadata&&(c=globalNewNotifMetadata[b],"phone_num_clean"in c&&(notifIsGroupedMsgNotif=checkIfThisNotifHasMultiMsgsGrouped({id:b,thread_id:c.phone_num_clean}))));return c}
function checkIfThisNotifHasMultiMsgsGrouped(b){var c=!1;if("undefined"!=typeof b&&"id"in b&&"thread_id"in b){var d=b.id;b=b.thread_id;b in globalIncomingMsgThreadNotifDetailsObj&&$(globalIncomingMsgThreadNotifDetailsObj[b]).each(function(b,f){$(f.msg_ids_of_grouped_msgs).each(function(b,e){if(d==notifID)return c=!0,!1});if(!0===c)return!1})}return c}
function buildRemindersAppIncomingSMSSnoozeURLParams(b){var c="&";if("undefined"!=typeof b&&b.hasOwnProperty("message")){var d=b.message,e=b="";d.hasOwnProperty("body")&&(b+=d.body.replace(new RegExp(/\n/g)," / "));if(d.hasOwnProperty("phone_num_clean")&&d.hasOwnProperty("phone_num")){e="";if(10==d.type)e+=getContactNameFromCaches(d.phone_num_clean,d.phone_num);else if(20==d.type){var f=getSanitizedPhoneNumberRemoveHyphensParenthesisSpaces(d.content_author,!0);e+=getContactNameFromCaches(f,d.content_author)}else e=
"";50<e.length&&(e=e.substr(0,46)+"...",_kmq.push(["record","CRX-Incoming-Message-Reminder-Contact-Name-Ellipsis"]));d=197-e.length;b.length>d&&(b=b.substring(0,d-4)+"...",_kmq.push(["record","CRX-Incoming-Message-Reminder-Msg-Body-Ellipsis"]))}c+="name="+encodeURIComponent(b+" - "+e)}return c}
function checkIfThereIsAlreadyAQuickReplyForThisThread(b,c){c=String(c);chrome.tabs.query({url:"https://mightytext.net/*"},function(d){console.log(d);console.log(c);0<d.length?$(d).each(function(e,f){if(-1<f.url.indexOf(c))return chrome.windows.update(f.windowId,{focused:!0},function(){console.log("found an existing QR window with this thread id")}),!1;d.length==e+1&&windowPopUpperRight(b)}):windowPopUpperRight(b)})}
function snoozeNotification(b){var c=new Date;c.getHours();c.getMinutes();var d=globalNewNotifMetadata[b];globalNewNotifMetadata[b].is_snoozed=!0;var e=getLocalizedAppString({key:"first_reminded"});-1==d.body.indexOf(e)&&(c="("+e+" "+cleanTimeDisplayPurposesOnlyTimeNoDay(c,!1)+")",d.body=81==d.type?c:globalNewNotifMetadata[b].body+" \r\n\r\n"+c);81==d.type?d.missed_call_reminder=!0:d.msg_reminder=!0;b='{"new_content":'+JSON.stringify(d,null,2)+"}";processIncomingPUSH(b)}
function handleBatteryNotif(b){chrome.tabs.create({url:"html/options.html",active:!0})}function invokeEnlargedMMSPictureMessageInNotif(b){"Mac"==globalUserOS?createFullSizePicWindow({notif_id:b}):(globalNewNotifMetadata[b].enlargeMMSMode=1,b='{"new_content":'+JSON.stringify(globalNewNotifMetadata[b],null,2)+"}",processIncomingPUSH(b))}
function createFullSizePicWindow(b){"undefined"!=typeof b&&b.hasOwnProperty("notif_id")&&chrome.windows.create({width:500,height:500,focused:!0,type:"popup",top:0,left:screen.width-507,url:baseUrl+"/imageserve?function=fetchFile&id="+globalNewNotifMetadata[b.notif_id].id},function(b){console.info("full-size picture window created",b)})}
function windowPopUpperRight(b){var c=checkForAdminOverridesInLocalStorage();0!=c&&null!=c&&alert("Warning: The webapp for this quick reply is loading from https://mightytext.net/"+c);if(-1<b.indexOf("quick-reply")){_gaq.push(["_trackEvent","Background","CRX-Rebuild-Legacy-Should-Not-Trigger","Old-Quick-Reply-Opened"]);c=400;var d=520}else c=getProperQuickReplyWidth(),d=600;chrome.windows.create({url:b,left:screen.width-(c+7),top:0,width:c,height:d,focused:!0,type:"popup"},function(b){chrome.windows.update(b.id,
{focused:!0});"Windows"==BrowserDetect.OS&&(setTimeout(function(){chrome.windows.update(b.id,{focused:!0})},250),setTimeout(function(){chrome.windows.update(b.id,{focused:!0})},500),setTimeout(function(){chrome.windows.update(b.id,{focused:!0})},1E3))})}
function commonActionsReplyToNotif(b){chrome.notifications.clear(b,function(b){});if(-1<b.indexOf("-picture")){var c=b.replace("-picture","");var d="https://mightytext.net/"+currentProductionPath+"/#mode=quick"+("&msgid="+globalNewNotifMetadata[c].id);c=globalNewNotifMetadata[c].phone_num_clean}else b in globalNewNotifMetadata&&(80==globalNewNotifMetadata[b].type||81==globalNewNotifMetadata[b].type)?d="https://mightytext.net/"+currentProductionPath+"/#mode=quick&num="+globalNewNotifMetadata[b].phone_num:
(d="https://mightytext.net/"+currentProductionPath+"/#mode=quick&msgid="+globalNewNotifMetadata[b].id,console.log(globalNewNotifMetadata[b])),c=globalNewNotifMetadata[b].phone_num_clean;checkIfThereIsAlreadyAQuickReplyForThisThread(d+("&thread_id="+c),c);markSingleMessageReadOnPhone(globalNewNotifMetadata[b].body,globalNewNotifMetadata[b].phone_num_clean)}
function markSingleMessageReadOnPhone(b,c){b=unescape(b);var d=c+"|"+b;console.log("attempting to mark message read on phone: "+b+" ---  "+c);sendOtherC2DM("mark_single_message_read",d,"msgid_local - not needed actually")}function getProperQuickReplyWidth(){return windowWidth=-1<window.navigator.appVersion.indexOf("Macintosh")?500:516}
function createUserNotLoggedInNotification(){if("1"==$.jStorage.get("crx_force_reload_no_signed_out_notif"))return!1;var b=determineIfNotifShouldRequireInteractionBasedOnOS({notif_options:{type:"basic",title:getLocalizedAppString({key:"not_signed_in_title"}),message:getLocalizedAppString({key:"notif_signed_in_content"}),iconUrl:"../img/48x48_MT_logo_boom_gradient_white.png",priority:2}});chrome.notifications.create("user_not_logged_in",b,function(b){console.log("created user_not_logged_in notif with the ID: "+
b);$.jStorage.set("crx_force_reload_no_signed_out_notif","1",{TTL:globalMsUntilShowNotLoggedInNotifAgain});recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:"user-not-logged-in"}});genericChromeNotifCreateCallback({notif_id:b,auto_dismiss:!1,notif_sound:!0})})}
function createCustomPopupNotifWindow(b){b=void 0===b?{}:b;try{chrome.windows.create({url:b.url,left:screen.width-370,top:0,width:356,height:b.height?b.height:134,focused:!0,type:b.type?b.type:"popup"},function(c){try{b.keep_track_of_window&&customNotifWindowIDArray.push({id:c.id,url:b.url,custom_mt_id_str:b.custom_id});if("on_create_cb"in b)b.on_create_cb();"Windows"==BrowserDetect.OS&&(setTimeout(function(){chrome.windows.update(a.id,{focused:!0})},250),setTimeout(function(){chrome.windows.update(a.id,
{focused:!0})},500),setTimeout(function(){chrome.windows.update(a.id,{focused:!0})},1E3))}catch(d){console.error("Unable to push custom notif window id to global array",d)}console.info("custom notif window created",c)})}catch(c){console.error("Error occurred when creating custom popup notif window",c)}}
function getImageForNotifFromDevice(b){var c=b.package_name,d="app_notif_icon|"+c,e=$.jStorage.get(d);if(e)createInAppDeviceNotificationAndDisplay(b,e);else{var f="../img/notifications/OS_Android.png";$.ajax({type:"GET",url:"https://mightytext.co:5001/?function=getsingleappinfo&appId="+encodeURIComponent(c),dataType:"text",timeout:3E3,success:function(c){c=JSON.parse(c);console.log(c);c.iconURL&&("url_not_found"!=c.iconURL&&("play_store_listing_not_found"==c.iconURL?$.jStorage.set(d,f,{TTL:6048E5}):
(f=c.iconURL,$.jStorage.set(d,f,{TTL:12096E5}))),createInAppDeviceNotificationAndDisplay(b,f))},error:function(c){colorConsole("error in getImageForNotifFromDevice","red");createInAppDeviceNotificationAndDisplay(b,f,chromeNotifKey)}})}}
function createInAppDeviceNotificationAndDisplay(b,c){0===c.indexOf("//")&&(c="https:"+c);var d="";b.app_name&&(d=b.app_name);var e="";b.ticker_text&&(e=b.ticker_text);var f="";b.data&&b.data["android.title"]&&(f=b.data["android.title"]);var k=d,h="";0<f.length&&(h=f);var g="";d="";b.data&&b.data["android.text"]&&(g=d=b.data["android.text"]);if(1>f.length||1>d.length)g=e,0<d.length&&(g+="\n"+d);b.data&&b.data["android.textLines"]&&(g+="\n"+b.data["android.textLines"]);d=b.app_name;h==g&&(g="");var l=
{type:"basic",title:k,message:h+"\n"+g,contextMessage:buildIncomingMessageContextMessage(),priority:2,eventTime:Date.now(),buttons:[{title:getLocalizedAppString({key:"dismiss_notif_on_phone"}),iconUrl:"../img/notifications/red_folder_stop.png"},{title:getLocalizedAppString({key:"phone_app_notif_more_options"}),iconUrl:"../img/notifications/red_block_icon.png"}]};e=new XMLHttpRequest;e.open("GET",c);e.responseType="blob";e.onload=function(){l.iconUrl=window.URL.createObjectURL(this.response);displayDeviceNotif(l,
b)};e.timeout=2E3;e.ontimeout=function(){l.iconUrl="../img/notifications/OS_Android.png";displayDeviceNotif(l,b)};e.send(null)}function dismissNotif(b,c,d){sendOtherC2DM("cancel_single_device_notification",b+"|"+c+"|"+d)}
function displayDeviceNotif(b,c){chrome.notifications.create("device-notification-"+c.ts_post,b,function(d){recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:"phone-app-notif"}});var e=String(c.ts_post);deviceNotifManagerArray[e].app_img_url=b.iconUrl;deviceNotifManagerArray[e].app_notif_message=b.message;10>Math.floor(100*Math.random())&&_gaq.push(["_trackEvent","CRX","Device-Notif-Invoke-Sample-10pct",c.package_name]);"k"==google_username_currently_logged_in.charAt(0)&&_kmq.push(["record",
"Device-Notif-Invoke-Letter-K",{"Package-Name":c.package_name,Client:"CRX"}]);genericChromeNotifCreateCallback({notif_id:d,auto_dismiss:!1,notif_sound:!0})})}
function createNotificationForLatestContactsRefreshed(){var b={type:"basic",priority:2,title:getLocalizedAppString({key:"contacts_refresh_title"}),message:getLocalizedAppString({key:"contacts_refresh_content"}),contextMessage:buildIncomingMessageContextMessage(),iconUrl:"../img/notifications/contact_photos_refreshed.png"};chrome.notifications.create("latest-contacts-refreshed-from-phone",b,function(b){recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:"contacts-refreshed"}});
_gaq.push(["_trackEvent","CRX-Background","Contacts-Refreshed-From-Phone",""]);console.info('just created a notif with the ID: "'+b+'"');genericChromeNotifCreateCallback({notif_id:b,auto_dismiss:!1,notif_sound:!0})})}function OLD_getCurrentUserSystemStateThenSetAutoDismiss(b,c){chrome.idle.queryState(globalSystemIdleStatusThresholdInSeconds,function(d){colorConsole('Current system state: "'+d+'"',"purple");OLD_checkSystemStateThenSetAutoRemoveTimeOutForThisNotif(b,d,c)})}
function OLD_checkSystemStateThenSetAutoRemoveTimeOutForThisNotif(b,c){"locked"==c&&(colorConsole("Current system state is locked at: "+new Date+", setting removing this notification (ID): "+b+" in 3 minutes","purple"),setAutoRemoveTimeOutForThisNotif(b))}
function getCurrentIdleStateAndStoreThisNotifIDInJstorage(b){chrome.idle.queryState(globalSystemIdleStatusThresholdInSeconds,function(c){colorConsole('Current system state: "'+c+'"',"purple");"locked"==c&&(c=(new Date).getTime(),$.jStorage.set("locked-notif-"+b,c,{TTL:864E5}))})}
function clearOldLockedChromeNotificationsFromTray(){colorConsole("Checking to see if there are any notifications that were created while the system was locked.","#3D4C87");chrome.notifications.getAll(function(b){console.log(b);$.each(b,function(b,d){var c=$.jStorage.get("locked-notif-"+b,"locked-notif-not-found");colorConsole("This is the ID of a notification created by the CRX:","#3D4C87");console.log(b);if("locked-notif-not-found"!=c){c=parseInt(c);var f=((new Date).getTime()-c)/1E3;colorConsole("This is the ID of a notification created by the CRX while system was LOCKED:",
"#3D4C87");console.log({ts_locked_notif:c,time_since_locked_notif:f});600<f&&chrome.notifications.clear(b,function(c){c&&colorConsole("successfully cleared a notif id: "+b,"#3D4C87")})}})})}
function legacyIncomingMsgSnooze(b){if("undefined"!=typeof b&&b.hasOwnProperty("notif_id")){var c=b.notif_id;-1<globalNewNotifMetadata[c].body.indexOf("reminded")?(_gaq.push(["_trackEvent","CRX-Background","Notif-Click","Snooze-Button-Action-REPEAT"]),_kmq.push(["record","Snooze-Message-Notif-Click-Repeat",{Client:"CRX"}])):(markSingleMessageReadOnPhone(globalNewNotifMetadata[c].body,globalNewNotifMetadata[c].phone_num_clean),_gaq.push(["_trackEvent","CRX-Background","Notif-Click","Snooze-Button-Action-INITIAL"]),
_kmq.push(["record","Snooze-Message-Notif-Click-Initial",{Client:"CRX"}]));setTimeout(function(){snoozeNotification(c)},3E5)}}
function genericChromeNotifCreateCallback(b){if("undefined"!=typeof b&&b.hasOwnProperty("notif_id")){var c=b.notif_id;$.each({notif_sound:!0,auto_dismiss:!0},function(c,e){b.hasOwnProperty(c)||(b.key=e)});0!=b.notif_sound&&playNotificationTone();0!=b.auto_dismiss&&setAutoRemoveTimeOutForThisNotif(c,b.optional_notif_ref);getCurrentIdleStateAndStoreThisNotifIDInJstorage(c)}}
function displayScheduledMessageNotif(b){if("undefined"!=typeof b&&b.hasOwnProperty("scheduled_msg_info")){b=b.scheduled_msg_info;var c=b.phone_num,d=b.phone_num_clean,e=b.body,f=getContactNameFromCaches(d,c);c=CRX_genericGetThumbnailFromCaches(d,c);e={type:"basic",priority:2,title:getLocalizedAppString({key:"scheduled_msg_sent_notif_title"}),message:'"'+e+'" was sent to '+f+" by your phone",contextMessage:buildIncomingMessageContextMessage(),iconUrl:c};chrome.notifications.create("scheduled-msg-sent-"+
b.id,e,function(b){recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:"scheduled-msg-sent"}});genericChromeNotifCreateCallback({notif_id:b,auto_dismiss:!1,notif_sound:!0})})}}
function displayMediaUploadedNotif(b){if("undefined"!=typeof b&&b.hasOwnProperty("media_uploaded_info")&&b.media_uploaded_info.hasOwnProperty("id")){var c=b.media_uploaded_info.id;b=b.media_uploaded_info.type;var d=localStorage.getItem("notif_content"),e={type:"basic",title:getLocalizedAppString({key:"new_photo_synced"}),message:"",contextMessage:buildIncomingMessageContextMessage(),iconUrl:"../img/48x48_MT_logo_boom_gradient_white.png",priority:2,buttons:[{title:getLocalizedAppString({key:"view_media"}),
iconUrl:"../img/notifications/view_media.png"}]};"1"==d&&(additionalNotifOptions={iconUrl:baseUrl+"/media?function=fetchViaServingUrl&resize=300&id="+c},$.extend(e,additionalNotifOptions));71==b&&(e.type="basic",e.iconUrl="../img/notifications/video_uploaded.png",e.title=getLocalizedAppString({key:"new_video_synced"}),delete e.imageUrl);chrome.notifications.create("new_media_uploaded-"+c,e,function(b){recordNotificationAnalyticsEvent({options:{type:"notif-created",sub_type:"media-uploaded"}});genericChromeNotifCreateCallback({notif_id:b,
auto_dismiss:!1,notif_sound:!0})})}};