function initializePopup(){callGAInBackgroundPage("CRX","Popup-Menu-Invoke");callKMInBackgroundPage("Popup-Menu-Invoke",{Client:"CRX"});callKMInBackgroundPage("CRX-Rebuild-Popup-Menu-Invoke",{Client:"CRX"});$(".popupButton").on("click",function(){var a=$(this).data("message"),b=$(this).data("event"),c={},d=null;c[a]=!0;if("Send-To-Phone"==b||"Compose-New"==b)d="link","Send-To-Phone"==b&&(d=$(this).data("type"));callKMInBackgroundPage("Popup-Menu-Click-Option",{"Content-Type":d,Client:"CRX",Action:b});
callGAInBackgroundPage("CRX","Popup-Menu-Click-Option",b+"-link");"setReminder"==a?displayRemindersWidget():"openPhoneLive"==a?displayPhoneLiveView():"openPhoneDialer"==a?displayPhoneLiveView({view:"dialer"}):(chrome.runtime.sendMessage(c,function(a){console.log(a)}),window.close())});$(".phone-tab-shortcut").on("click",function(a){a.stopPropagation();a=$(this).attr("data-view");var b=$(this).closest(".popupButton").attr("data-event");callKMInBackgroundPage("Popup-Menu-Click-Option",{"Content-Type":"link",
Client:"CRX",Action:b});callGAInBackgroundPage("CRX","Popup-Menu-Click-Option",b+"-link");callGAInBackgroundPage("CRX","Popup-Menu-Click-Live-Phone-View-Shortcut-Option",a);displayPhoneLiveView({view:a})});$(".nav-btn").on("click",function(a){a.preventDefault();a.stopPropagation();var b=$(this).attr("action");if("settings"==b){var c=".popupContainer, .settings-btn, .notif-toggle";var d=".settings-iframe";$(d).attr("src");$(d).attr("src","").attr("src","../html/options.html")}else"home"==b&&(c=".settings-iframe",
d=".popupContainer, .settings-btn, .notif-toggle",setupPopupFooterActionBtns());$(c).fadeOut(150,function(){$(d).fadeIn(250);$(".nav-buttons").attr("data-inview",b)})});localizeStringsInUI({strings_elem:$(".popup-option-name, .mighty-tooltip"),additional_callback:function(a){$(a).hasClass("new-feature")&&addNewFeatureBadge({popup_option:a})}});$("body").attr("lang",navigator.language);determineIfRemindersUIShouldBeShown();determineIfPhoneLiveViewUIShouldBeShown();setupPopupFooterActionBtns(!0);getCurrentActiveTabInfo();
insertBatStatBar();addTooltips();determineIfUserIsPro()}function checkIfUserHasMinAPKVersionInstalled(){return!0}function determineIfUserIsPro(){chrome.runtime.sendMessage({check_user_pro_status:!0},function(a){"object"==typeof a&&a.hasOwnProperty("user_is_pro")&&!1===a.user_is_pro&&$("#goPro").show()})}function determineIfPhoneLiveViewUIShouldBeShown(){if(checkIfUserHasMinAPKVersionInstalled()){var a=$("#livePhoneView");$(a).show()}}
function determineIfRemindersUIShouldBeShown(){"user-in-exp"==$.jStorage.get("mt_reminders_experiment","exp-flag-not-set")&&$("#reminderButtons").show()}
function displayPhoneLiveView(a){var b="notifs";$(".popupContainer, .settings-btn, .notif-toggle").hide();$("body").addClass("loading-pnlv");"undefined"!=typeof a&&a.hasOwnProperty("view")&&(b=a.view);var c=$('<iframe class="phone-live-view-iframe" src="https://mightytext.net/'+currentProductionPath+"/#mode=live-phone-view&client=crx-popup&view="+b+'"></iframe>').appendTo("body");var d=setTimeout(function(){callKMInBackgroundPage("new-pnlv-wa-iframe-timeout-executed");displayIframeTimeoutError({iframe:c,
app:"pnlv",refresh_callback:function(){var a={};-1<$(c).attr("src").indexOf("dialer")&&(a={view:"dialer"});displayPhoneLiveView(a)}});$("body").removeClass("loading-pnlv")},1E4);window.addEventListener("message",function(a){setPNLVIframeMessageListener(a,d)});"notifs"==b&&tellBGUserLoadedPNLV()}
function displayIframeTimeoutError(a){var b=a.iframe;$(b).attr("src");var c='<div class="load-error-container '+a.app+'">';c=c+'<div class="vertical-align-helper"></div><div class="load-error-inner"><i id="load-error-icon" class="fa fa-fw fa-times-circle"></i>'+getLocalizedAppString({key:"unable_to_load_mt_iframe"});c+='<div class="refresh-btn-wrapper"><button id="refresh-iframe-btn" class="mighty-btn mighty-holo">'+getLocalizedAppString({key:"retry"})+"</button></div>";var d=$(c+"</div></div>").insertAfter(b);
$(b).remove();b=$(d).find("#refresh-iframe-btn");$(b).on("click",function(){callKMInBackgroundPage("new-pnlv-wa-iframe-timeout-retry-load");$(d).fadeOut(function(){$(this).remove();a.refresh_callback()})})}
function setPNLVIframeMessageListener(a,b){if("https://mightytext.net"==a.origin){var c=a.data;c.hasOwnProperty("check_for_existing_pnlv_popout")?checkForExistingPhoneLiveViewPopout({focus_existing:!0,popout_if_none_found:!0,pnlv_popout_url_sub_str:c.pnlv_popout_url_substring,viewOnLoad:c.view}):c.hasOwnProperty("expand_window")?1!=c.expand_window?$("body").removeClass("send_file_to_phone_expand"):$("body").addClass("send_file_to_phone_expand"):c.hasOwnProperty("live_phone_view_load_success")?(clearTimeout(b),
$(".phone-live-view-iframe").show(),$("body").removeClass("loading-pnlv")):console.error(new Date+" Unrecognized message sent from mt.net",c)}else console.error("unrecognized message origin: ",a.origin)}
function checkForExistingPhoneLiveViewPopout(a){var b=a.pnlv_popout_url_sub_str,c=b;a.hasOwnProperty("viewOnLoad")&&(c+="&view="+a.viewOnLoad);chrome.tabs.query({windowType:"popup"},function(d){0<d.length?$(d).each(function(d,f){f.hasOwnProperty("url")?-1<f.url.indexOf(b)&&a.hasOwnProperty("focus_existing")?f.hasOwnProperty("windowId")&&chrome.windows.update(f.windowId,{focused:!0}):a.hasOwnProperty("popout_if_none_found")&&popoutPhoneNotifLiveView({url:c}):console.error(new Date+' No "url" property found in this tab object')}):
a.hasOwnProperty("popout_if_none_found")&&popoutPhoneNotifLiveView({url:c})})}function popoutPhoneNotifLiveView(a){if(a.hasOwnProperty("url")){var b=a.url,c=screen.width-357,d=39;-1<navigator.appVersion.indexOf("Mac")&&(d=22);d=600+d;console.info("trying to create a window, options: ",a);chrome.windows.create({width:350,height:d,focused:!0,left:c,type:"popup",url:b+"&client=crx-popout"})}}function tellBGUserLoadedPNLV(){chrome.runtime.sendMessage({user_loaded_phone_notif_live_view:!0})}
function displayRemindersWidget(){$(".popupContainer, .settings-btn, .notif-toggle").fadeOut(50,function(){$("body").addClass("loading-create-reminders")});var a=setTimeout(function(){$("body").removeClass("loading-create-reminders");displayIframeTimeoutError({iframe:$(".reminders-iframe"),app:"create-reminder",refresh_callback:function(){displayRemindersWidget()}})},1E4);$('<iframe class="reminders-iframe" src=""></iframe>').appendTo("body").attr("src","").attr("src",remindersAppUrl+"#mode=create").on("load",
function(){$("body").removeClass("loading-create-reminders");clearTimeout(a);$(this).fadeIn(50);window.addEventListener("message",handleIframedRemindersAppMessages)})}function handleIframedRemindersAppMessages(a){"closeIframe"==a.data?window.close():void 0!=a.data.action?"resizeIframe"==a.data.action?(a=a.data.dimensions,$(".reminders-iframe").css(a)):console.error("unrecognized message JSON: "+a.data):console.error("unrecognized message: "+a.data)}
function requestBatteryStatus(){chrome.runtime.sendMessage({requestPhoneStatusNotCollapsed:!0,high_priority_gcm:!0},function(a){console.log(a)})}
chrome.runtime.onMessage.addListener(function(a,b,c){if(a.phoneStatus){var d=a.phoneStatus;a=d.battery_level;b=d.battery_is_charging;d=String(d.ts_phone_utc/1E3);console.log("got a battery status");var e="";"false"!=b&&(e='<div id="chargingIcon"><span class="font-awesome-container"><i class="fa fa-bolt"></i></span></div>');updateBatteryStatusDisplay(a,e,d);c({popup_received_phone_status:!0})}else a.activeTabInfo&&checkActiveTabURLAgainstOurArrayOfApprovedHosts({url:a.activeTabInfo.url})});
function insertBatStatBar(){1>$("div.bat-wrap-holder").length&&$('<div class="bat-wrap-holder"><div id="batstatInitial" class="newbatterywrap mighty-tooltip" tooltip-content="'+getLocalizedAppString({key:"phone_bat_stat"})+'"></div></div>').prependTo("#popup-footer");var a=$.jStorage.get("latest_phone_status");if(void 0!=a){var b="";"false"!=a.battery_is_charging&&(b='<div id="chargingIcon"><span class="font-awesome-container"><i class="fa fa-bolt"></i></span></div>');updateBatteryStatusDisplay(a.battery_level,
b,"")}requestBatteryStatus()}
function updateBatteryStatusDisplay(a,b,c){c=Math.round(a);var d='<div class="baticon"><span class="font-awesome-container"><i class="fa fa-mobile"></i></span></div><div class="mainCRXBattery"><div class="batwrap"><div class="batshell"><span class="batpercent">'+c+'%</span><div class="batbar" style="width:'+a+'%"></div></div><div class="batnub"></div></div></div>     '+b,e=$(".baticon");console.log({object:e,length:e.length});1>e.length?$(".newbatterywrap").empty().append(d).hide().fadeIn(150).each(function(){console.log("batstat appended");updateBatBarColorToReflectCurrentBatLevel(a)}):
(d=$("#chargingIcon"),$(".batpercent").text(c+"%"),$(".batbar").css("width",a+"%"),updateBatBarColorToReflectCurrentBatLevel(a),0<b.length?1>d.length&&$(".newbatterywrap").append(b):$(d).remove())}
function updateBatBarColorToReflectCurrentBatLevel(a){100<=a?($(".batbar").css("background-color","#67b422"),$(".batnub").css("background-color","#67b422")):60<=a?$(".batbar").css("background-color","#67b422"):20<=a&&59>=a?($(".batbar").css("background-color","#ffe400"),$(".batpercent").addClass("legible")):19>=a&&$(".batbar").css("background-color","#f02828")}
function appendAppropriateAppIconToMenu(a){var b="",c="",d="";"google.com/maps"==a||"google.co.uk/maps"==a?(b="map-marker.png",c=getLocalizedAppString({key:"open_map_on_phone"}),d="google-maps"):"youtube.com/watch"==a?(b="youtube_play.png",c=getLocalizedAppString({key:"play_vid_on_phone"}),d="youtube"):"yelp.com/biz"==a&&(b="yelp_icon.png",c=getLocalizedAppString({key:"open_review_on_phone"}),d="yelp");$("[data-message='pushThisPageToPhone'").find("img").attr("src","../img/web-to-phone/"+b);$("[data-message='pushThisPageToPhone'").find("span").text(c);
$("[data-message='pushThisPageToPhone'").attr("data-type",d)}
function setupPopupFooterActionBtns(a){var b=$(".notif-toggle");setCorrectNotifToggleValue(b,window.localStorage.global_notifications);if(a)$(b).on("click",function(){var a=$(this).attr("value");callKMInBackgroundPage("user-changed-crx-setting",{crx_setting_name:"global_notifications",crx_setting_value_set:a,Client:"CRX"});setCorrectNotifToggleValue(this,a,!0);chrome.runtime.sendMessage({setProperBrowserActionIcon:!0},function(a){console.log(a)})})}
function setCorrectNotifToggleValue(a,b,c){var d="notifications_active";if("1"==b){d="notifications_off";var e="enabled";var f="disabled";var g="0"}else"0"==b&&(e="disabled",f="enabled",g="1");c?(console.info(g),$(a).removeClass(e).addClass(f).attr("value",g),window.localStorage.global_notifications=g,notifyUserOfIncomingMessageNotificationToggle(g)):($(a).removeClass(f).addClass(e).attr("value",b),d="0"==b?"notifications_off":"notifications_active");$(a).text(d)}
function notifyUserOfIncomingMessageNotificationToggle(a){if("0"==a){a="off";var b="../img/notifications/global_notifications_off.png";confirmNotifTitle=getLocalizedAppString({key:"global_notifs_off_confirm"})}else"1"==a&&(a="on",b="../img/notifications/96x96-global-notifs-on.png",confirmNotifTitle=getLocalizedAppString({key:"global_notifs_on_confirm"}));var c={type:"basic",priority:2,title:"",message:"",contextMessage:buildIncomingMessageContextMessage()},d={title:confirmNotifTitle,iconUrl:b};chrome.notifications.clear("user-global-notif-setting-toggle",
function(){$.extend(c,d);console.info("notif options",c);chrome.notifications.create("user-global-notif-setting-toggle",c,function(a){chrome.runtime.sendMessage({record_mt_stats_event:!0,notif_event:!0,event_options:{type:"notif-created",sub_type:"user-global-notif-setting-toggle"}});genericChromeNotifCreateCallback({notif_id:a,auto_dismiss:!1,notif_sound:!1})})})}
function addTooltips(){$(".mighty-tooltip").each(function(a,b){var c=$(b).attr("tooltip-content");$(b).tooltip("destroy").tooltip({trigger:"hover",title:c,placement:"top",delay:{show:150,hide:100}})}).on("click",function(){$(this).tooltip("hide")})}
function setLocalizedStringsInPopup(){$(".popup-option-name").each(function(){var a=$(this).attr("local-key");a=getLocalizedAppString({key:a});$(this).html(a);$(this).hasClass("new-feature")&&addNewFeatureBadge({popup_option:this})});$(".mighty-tooltip").each(function(){var a=$(this).attr("local-key");a=getLocalizedAppString({key:a});$(this).attr("tooltip-content",a)})}
function addNewFeatureBadge(a){if("undefined"!=typeof a&&a.hasOwnProperty("popup_option")){var b=' <sup class="new-badge">'+getLocalizedAppString({key:"new_feature_badge"})+"!</sup>";$(a.popup_option).append(b)}}$(document).on("ready",function(){setTimeout(function(){initializePopup()},0)});
function setupArrowKeyNavigationListeners(){$(document).on("keydown",function(a){if(36<a.keyCode<41){var b=$(".popupButton:visible");b.get(0);var c=0;$(b).each(function(a,b){if($(b).is(":focus"))return c=a,!1});if(39==a.keyCode||40==a.keyCode)newBtnIndex=c+1;if(38==a.keyCode||37==a.keyCode)newBtnIndex=c-1;0>newBtnIndex?newBtnIndex=b.length-1:newBtnIndex==b.length&&(newBtnIndex=0);b.get(newBtnIndex).focus()}})};