var options=function(){var k=null,l=void 0,b={},n={},w=function(){for(var b in options.defaultSettings){var a=options.defaultSettings[b],c=document.querySelector('input[data-option="'+b+'"]');if(null===c)console.log("El not found!",b);else if(-1!==["text","number","password"].indexOf(c.type)){if(c.value=options.settings[b]!==a?options.settings[b]:"",a||""===a||0===a)c.placeholder=a}else"checkbox"===c.type?c.checked=!!options.settings[b]:"radio"===c.type&&(a=document.querySelector('input[data-option="'+
b+'"][value="'+options.settings[b]+'"]'),null!==a&&(c=a),c.checked=!0)}},p=function(){var b=location.hash.substr(1)||"client";b=document.querySelector('a[data-page="'+b+'"]');null===b&&(b=document.querySelector('a[data-page="client"]'));b.dispatchEvent(new CustomEvent("click",{bubbles:!0}))},m=function(b){var a=b.target;if("INPUT"===a.tagName&&(b=a.dataset.option)){if("checkbox"===a.type)var c=a.checked?1:0;else if("radio"===a.type)c=parseInt(a.value);else if("number"===a.type){c=parseInt(a.value);
isNaN(c)&&(c=parseInt(a.placeholder));var d=parseInt(a.min);!isNaN(d)&&c<d&&(c=d,a.value=c);if(isNaN(c))return}else-1!==["text","password"].indexOf(a.type)&&(c=a.value,a=a.placeholder,!c&&a&&(c=a));a={};a[b]=c;var f=this.cb;mono.storage.local.set(a,function(){mono.sendMessage({action:"reloadSettings"},f)})}},q=function(b){mono.storage.local.get(null,function(a){b&&b(JSON.stringify(a))})},x=function(b){mono.storage.local.clear();var a={},c;for(c in b){var d=b[c];!1!==b.hasOwnProperty(c)&&null!==d&&
(a[c]=d)}mono.storage.local.set(a,function(){mono.sendMessage({action:"reloadSettings"},function(){window.location.reload()})})},y=function(){b.backupUpdateBtn.on("click",function(){q(function(d){b.backupInp.val(d)})});b.restoreBtn.on("click",function(){try{var d=JSON.parse(b.restoreInp.val())}catch(a){return alert(options.language.OV_FL_ERROR+"\n"+a)}x(d)});b.clearCloudStorageBtn.on("click",function(){mono.storage.sync.clear();b.getFromCloudBtn.prop("disabled",!0)});b.saveInCloudBtn.on("click",function(){var d=
this;d.disabled=!0;setTimeout(function(){d.disabled=!1},750);q(function(a){mono.storage.sync.set({backup:a},function(){b.getFromCloudBtn.prop("disabled",!1)})})});b.getFromCloudBtn.on("click",function(){mono.storage.sync.get("backup",function(d){b.restoreInp.val(d.backup)})})},z=function(b){b=(b||document).querySelectorAll("[data-lang]");for(var a=0,c;c=b[a];a++)for(var d=c.dataset.lang.split("|"),f=0,g;g=d[f];f++){g=g.split(",");var h=options.language[g.shift()];void 0===h?console.log("Language string is not found!",
c.dataset.lang):0!==g.length?g.forEach(function(b){if("text"===b)return c.textContent=h,1;c.setAttribute(b,h)}):"DIV"===c.tagName?c.title=h:-1!=="A LEGEND SPAN LI TH P OPTION BUTTON H2 H3".split(" ").indexOf(c.tagName)?c.textContent=h:"INPUT"===c.tagName?c.value=h:console.log("Tag name not found!",c.tagName)}},r=function(){mono.sendMessage({action:"getDirList"},function(d){var a=b.dirList;a.textContent="";if(d=d["download-dirs"]){for(var c=0,e;e=d[c];c++)a.appendChild(utils.create("option",{value:c,
text:e.path,data:{available:e.available}}));a.selectedIndex=0}else a.selectedIndex=-1;a.dispatchEvent(new CustomEvent("change"))})},A=function(d){for(var a=0,c;c=d[a];a++)b.folderList.appendChild(utils.create("option",{text:(c[2]?"["+c[2]+"] ":"")+c[1],data:{dir:c[0],subPath:c[1],label:c[2]||""}}))},B=window.folderSaveList=function(){for(var d=[],a=b.folderList.childNodes,c=0,e;e=a[c];c++)d.push([e.dataset.dir,e.dataset.subPath,e.dataset.label]);mono.storage.local.set({folderList:d},function(){mono.sendMessage({action:"reloadSettings"})})},
C=function(d){for(var a=0,c;c=d[a];a++)b.labelList.appendChild(utils.create("option",{text:c,data:{label:c}}))},D=window.labelSaveList=function(){for(var d=[],a=b.labelList.childNodes,c=0,e;e=a[c];c++)d.push(e.dataset.label);mono.storage.local.set({labelList:d},function(){mono.sendMessage({action:"reloadSettings"})})},t=function(d){for(var a=[],c=b[d+"List"].childNodes,e=0,f;f=c[e];e++)f.selected&&a.push(f);for(e=0;f=a[e];e++)f.parentNode.removeChild(f);window[d+"SaveList"]()},u=function(d){var a=
b[d+"List"],c=a.selectedIndex;-1!==c&&(c=a.childNodes[c],c.previousElementSibling&&(a.insertBefore(c,c.previousElementSibling),window[d+"SaveList"]()))},v=function(d){var a=b[d+"List"],c=a.selectedIndex;if(-1!==c){c=a.childNodes[c];var e=c.nextElementSibling;e&&(e.nextElementSibling?a.insertBefore(c,e.nextElementSibling):a.appendChild(c),window[d+"SaveList"]())}},E=function(){var b=!1,a=document.querySelector('input[data-option="badgeColor"]'),c=$(a.parentNode.querySelector(".selectColor")),e=options.settings.badgeColor;
c.data("color","rgba("+e+")");c.css("backgroundColor","rgba("+e+")");a.addEventListener("keyup",function(){c.colorpicker("setValue","rgba("+a.value+")")});a.addEventListener("focus",function(){b=!0});a.addEventListener("blur",function(){b=!1});c.colorpicker();c.on("changeColor.colorpicker",function(d){d=d.color.toRGB();e=d=d.r+","+d.g+","+d.b+","+d.a;c.css("backgroundColor","rgba("+d+")");mono.sendMessage({action:"changeBadgeColor",color:d});b||(a.value=e)});c.on("hidePicker.colorpicker",function(){a.dispatchEvent(new CustomEvent("keyup"))})};
return{start:function(){mono.storage.local.get(["folderList","labelList"],function(d){utils.joinMessages([{action:"getLanguage"},{action:"getSettings"},{action:"getTrColumnArray"},{action:"getFlColumnArray"},{action:"getDefaultSettings"}]).then(function(a){options.settings=a.getSettings;options.defaultSettings=a.getDefaultSettings;options.language=a.getLanguage;var c=document.getElementById("language");a="ru en fr zh-CN es pt-BR".split(" ").indexOf(options.language.lang);-1===a&&(a=1);c.selectedIndex=
a;c.addEventListener("change",function(){mono.storage.local.set({language:c.childNodes[c.selectedIndex].value},function(){mono.sendMessage({action:"reloadSettings"},function(){location.reload()})})});"ru"!==options.language.lang&&(document.querySelector(".cirilicFixs").style.display="none");z();document.body.classList.remove("loading");b.folderList=document.getElementById("folderList");A(d.folderList||[]);b.subPath=document.getElementById("subPath");b.pathLabel=document.getElementById("pathLabel");
b.addSubPath=document.getElementById("addSubPath");b.addSubPath.addEventListener("click",function(){var a=b.dirList.selectedIndex;if(-1!==a){a=parseInt(b.dirList.childNodes[a].value);var c=b.subPath.value;if(c){var d=b.pathLabel.value;b.folderList.appendChild(utils.create("option",{text:(d?"["+d+"] ":"")+c,data:{dir:a,subPath:c,label:d}}));b.subPath.value="";b.pathLabel.value="";B()}}});b.subPath.addEventListener("keydown",function(a){13===a.keyCode&&b.addSubPath.dispatchEvent(new CustomEvent("click"))});
b.pathLabel.addEventListener("keydown",function(a){13===a.keyCode&&b.addSubPath.dispatchEvent(new CustomEvent("click"))});b.label=document.getElementById("label");b.labelList=document.getElementById("labelList");C(d.labelList||[]);b.addLabel=document.getElementById("addLabel");b.addLabel.addEventListener("click",function(){var a=b.label.value;a&&(b.labelList.appendChild(utils.create("option",{text:a,data:{label:a}})),b.label.value="",D())});b.label.addEventListener("keydown",function(a){13===a.keyCode&&
b.addLabel.dispatchEvent(new CustomEvent("click"))});b.folderDeleteSelected=document.getElementById("folderDeleteSelected");b.folderDeleteSelected.addEventListener("click",t.bind(null,"folder"));b.folderUp=document.getElementById("folderUp");b.folderUp.addEventListener("click",u.bind(null,"folder"));b.folderDown=document.getElementById("folderDown");b.folderDown.addEventListener("click",v.bind(null,"folder"));b.labelDeleteSelected=document.getElementById("labelDeleteSelected");b.labelDeleteSelected.addEventListener("click",
t.bind(null,"label"));b.labelUp=document.getElementById("labelUp");b.labelUp.addEventListener("click",u.bind(null,"label"));b.labelDown=document.getElementById("labelDown");b.labelDown.addEventListener("click",v.bind(null,"label"));b.backupUpdateBtn=$("#backupUpdate");b.restoreBtn=$("#restoreBtn");b.saveInCloudBtn=$("#saveInCloud");b.getFromCloudBtn=$("#getFromCloudBtn");b.clearCloudStorageBtn=$("#clearCloudStorage");b.backupInp=$("#backupInp");b.restoreInp=$("#restoreInp");w();E();y();b.menu=document.querySelector(".menu");
b.menu.addEventListener("click",function(a){a=a.target;"A"!==a.tagName||a.classList.contains("active")||(l&&l.classList.remove("active"),l=a,l.classList.add("active"),k&&k.classList.remove("active"),a=a.dataset.page,k=document.querySelector(".page."+a),k.classList.add("active"),"backup"===a&&b.backupUpdateBtn.trigger("click"),"restore"===a&&mono.storage.sync.get("backup",function(a){void 0===a.backup&&b.getFromCloudBtn.prop("disabled",!0)}),"ctx"===a&&r())});window.addEventListener("hashchange",p);
p();b.clientCheckBtn=document.getElementById("clientCheckBtn");b.clientCheckBtn.addEventListener("click",function(a){var b=document.getElementById("clientStatus");b.textContent="";b.appendChild(utils.create("img",{src:"images/loading.gif"}));mono.sendMessage({action:"checkSettings"},function(a){b.textContent="";if(a.error)a=utils.create("span",{text:a.error,style:{color:"red"}});else if(a=utils.create("span",{text:options.language.DLG_BTN_OK,style:{color:"green"}}),!mono.isTab())return window.location=
"manager.html";b.appendChild(a);clearTimeout(n.statusTimer);n.statusTimer=setTimeout(function(){b.textContent=""},2500)})});b.dirList=document.getElementById("dirList");b.dirList.addEventListener("change",function(){var a=this.childNodes[this.selectedIndex],c=-1;if(a){a=1048576*a.dataset.available;var d=void 0;c=options.language.sizeList;c=JSON.parse(c);void 0===d&&(d="n/a");if(0===a)c=d;else if(d=parseInt(Math.floor(Math.log(a)/Math.log(1024))),0===d)c=a/Math.pow(1024,d)+" "+c[d];else{var e=1;2<
d&&(e=2);c=(a/Math.pow(1024,d)).toFixed(e)+" "+c[d]}b.addSubPath.disabled=!1}else b.addSubPath.disabled=!0;document.getElementById("availableCount").textContent=c});b.updateDirList=document.getElementById("updateDirList");b.updateDirList.addEventListener("click",function(){r()});var e=document.querySelectorAll('input[data-option="login"], input[data-option="password"], input[data-option="ip"], input[data-option="port"]');a=0;for(var f;f=e[a];a++)f.addEventListener("keydown",function(a){13===a.keyCode&&
m.call({cb:function(){b.clientCheckBtn.dispatchEvent(new CustomEvent("click"))}},{target:this})});e=document.querySelectorAll("input[type=text], input[type=password], input[type=number]");for(a=0;f=e[a];a++)f.addEventListener("keyup",utils.debounce(m,500));document.body.addEventListener("click",m)})})}}}();mono.onReady(function(){options.start()});
